import os

project = 'bubo-1'
zone = 'us-west1-b'
gs_bucket = 'bubo-data'
gs_data_dir = f'gs://{gs_bucket}/v0/data'  # Mirror of data_dir in gs

# TODO Find a cleaner way to do this
#   - [No memory of why these need to be absolute... :/]
_maybe_code_dirs = [
    '/Users/danb/hack/birdgram/model',  # Local dev (osx)
    '/app',  # Remote deploy (docker/linux)
]
for _maybe_code_dir in _maybe_code_dirs:
    if os.path.exists(_maybe_code_dir):
        code_dir = _maybe_code_dir
        break
else:
    raise Exception(f'Found none of these dirs to use as code_dir: {_maybe_code_dirs}')

# Dirs
#   - code/
bin_dir = f'{code_dir}/bin'
data_dir = f'{code_dir}/data'
#   - data/
cache_dir = f'{data_dir}/cache'
artifact_dir = f'{data_dir}/artifacts'
hand_labels_dir = f'{data_dir}/hand-labels'
#   - data/uploads/
uploads_dir = f'{data_dir}/uploads'
uploads_recs_dir = f'{uploads_dir}/recs'
#   - data/cache/
cache_audio_dir = f'{cache_dir}/audio'
#   - mobile/
mobile_dir = f'{code_dir}/../mobile'
mobile_ios_tests_data_dir = f'{mobile_dir}/ios/Tests/data'

standard_sample_rate_hz = 22050  # Can resolve 11025Hz (by Nyquist), which most/all birds are below
default_log_ylim_min_hz = 512  # Most/all birds are above 512Hz (but make sure to clip noise below 512Hz)

unk_species = '_UNK'
unk_species_com_name = 'Unknown'
unk_species_taxon_id = 'TC___UNK'
unk_species_species_code = '___unk'

mul_species = '_MUL'
mul_species_com_name = 'Multiple species'
mul_species_taxon_id = 'TC___MUL'
mul_species_species_code = '___mul'

no_species = '_NON'
no_species_com_name = 'No species'
no_species_taxon_id = 'TC___NON'
no_species_species_code = '___non'

##
# countries

countries = dict(
    na=['United States', 'Canada', 'Mexico'],  # North America minus Central America
    ca=['Belize', 'Costa Rica', 'El Salvador', 'Guatemala', 'Honduras', 'Nicaragua', 'Panama'],
    sa=[
        'Argentina', 'Bolivia', 'Brazil', 'Chile', 'Colombia', 'Ecuador', 'Falkland Islands', 'French Guiana', 'Guyana',
        'Paraguay', 'Peru', 'Suriname', 'Uruguay', 'Venezuela',
    ],
)
countries = dict(**countries,
    am=countries['na'] + countries['ca'] + countries['sa'],
)

##
# com_names

com_names = dict(

    # WARNING Ensure this is the only n_species=4 dataset to avoid colliding with other n_species=4 model ids
    dan4=('ebird', ["Bewick's Wren", "House Wren", "Song Sparrow", "Spotted Towhee"]),
    dan5=('ebird', ["Bewick's Wren", "House Wren", "Song Sparrow", "Spotted Towhee", "Pacific-slope Flycatcher"]),

    ggow=('ebird', ["Great Gray Owl"]),

    # The first set of hand-curated species I started training with, based on Mitchell Canyon / Coyote Hills checklists
    #   - XXX Not very valuable to hold on to
    #   - WARNING Keep this ≠168 species to avoid colliding with n_species=168 model ids in the eval notebooks
    dan170=('ebird', [
        "Mountain Quail", "Scaled Quail", "California Quail", "Montezuma Quail", "Sooty Grouse", "Wild Turkey",
        "Double-crested Cormorant", "Least Bittern", "Great Blue Heron", "Great Egret", "Snowy Egret", "Green Heron",
        "Black-crowned Night-Heron", "Osprey", "White-tailed Kite", "Golden Eagle",
        "Northern Harrier", "Sharp-shinned Hawk", "Cooper's Hawk", "Bald Eagle", "Red-shouldered Hawk", "Red-tailed Hawk",
        "Killdeer", "Rock Pigeon", "Band-tailed Pigeon", "Eurasian Collared-Dove", "Mourning Dove", "Western Screech-Owl",
        "Great Horned Owl", "Burrowing Owl", "Common Nighthawk", "Common Poorwill", "White-throated Swift",
        "Anna's Hummingbird", "Rufous Hummingbird", "Allen's Hummingbird", "Belted Kingfisher", "Acorn Woodpecker",
        "Red-breasted Sapsucker", "Nuttall's Woodpecker", "Downy Woodpecker", "Hairy Woodpecker", "Northern Flicker",
        "Pileated Woodpecker", "American Kestrel", "Merlin", "Peregrine Falcon", "Olive-sided Flycatcher",
        "Western Wood-Pewee", "Pacific-slope Flycatcher", "Black Phoebe", "Say's Phoebe", "Ash-throated Flycatcher",
        "Western Kingbird", "Hutton's Vireo", "Cassin's Vireo", "Warbling Vireo", "Steller's Jay", "California Scrub-Jay",
        "Black-billed Magpie", "Yellow-billed Magpie", "Clark's Nutcracker", "American Crow", "Common Raven",
        "Northern Rough-winged Swallow", "Purple Martin", "Tree Swallow", "Violet-green Swallow", "Barn Swallow",
        "Cliff Swallow", "Carolina Chickadee", "Black-capped Chickadee", "Mountain Chickadee", "Chestnut-backed Chickadee",
        "Boreal Chickadee", "Oak Titmouse", "Tufted Titmouse", "Black-crested Titmouse", "Bushtit", "Red-breasted Nuthatch",
        "White-breasted Nuthatch", "Pygmy Nuthatch", "Brown Creeper", "Rock Wren", "Canyon Wren", "House Wren",
        "Pacific Wren", "Winter Wren", "Sedge Wren", "Marsh Wren", "Carolina Wren", "Bewick's Wren", "Cactus Wren",
        "Blue-gray Gnatcatcher", "Golden-crowned Kinglet", "Ruby-crowned Kinglet", "Wrentit", "Western Bluebird",
        "Mountain Bluebird", "Swainson's Thrush", "Hermit Thrush", "Wood Thrush", "American Robin", "Varied Thrush",
        "Gray Catbird", "California Thrasher", "Northern Mockingbird", "European Starling", "Cedar Waxwing", "Phainopepla",
        "Black-and-white Warbler", "Orange-crowned Warbler", "Nashville Warbler", "MacGillivray's Warbler",
        "Common Yellowthroat", "American Redstart", "Cape May Warbler", "Cerulean Warbler", "Magnolia Warbler",
        "Bay-breasted Warbler", "Yellow Warbler", "Blackpoll Warbler", "Black-throated Blue Warbler", "Palm Warbler",
        "Yellow-rumped Warbler",
        "Yellow-throated Warbler", "Black-throated Gray Warbler", "Townsend's Warbler", "Hermit Warbler",
        "Golden-cheeked Warbler", "Black-throated Green Warbler", "Wilson's Warbler", "Chipping Sparrow", "Lark Sparrow",
        "Fox Sparrow", "Dark-eyed Junco", "White-crowned Sparrow", "Golden-crowned Sparrow", "Bell's Sparrow",
        "Savannah Sparrow", "Song Sparrow", "Lincoln's Sparrow", "Swamp Sparrow", "Canyon Towhee", "California Towhee",
        "Rufous-crowned Sparrow", "Spotted Towhee", "Summer Tanager", "Scarlet Tanager", "Western Tanager",
        "Northern Cardinal", "Black-headed Grosbeak", "Blue Grosbeak", "Lazuli Bunting", "Western Meadowlark",
        "Hooded Oriole", "Bullock's Oriole", "Red-winged Blackbird", "Tricolored Blackbird", "Brown-headed Cowbird",
        "Brewer's Blackbird", "Common Grackle", "Great-tailed Grackle", "Black Rosy-Finch", "House Finch", "Purple Finch",
        "Pine Siskin", "Lesser Goldfinch", "American Goldfinch", "House Sparrow",
    ]),

    # CA (sp=334): All xc com_name's that have ≥1 rec in CA
    #   from notebooks import *
    #   import pprint
    #   (xc.metadata
    #       [lambda df: pd.notnull(df.species)]
    #       [lambda df: (df.country == 'United States') & df.locality.str.endswith('California')]
    #       .pipe(df_remove_unused_categories).com_name.sort_values()
    #       .pipe(puts, f=lambda s: len(s.unique()))
    #       .pipe(lambda s:
    #           pprint.pprint(s.unique().tolist(), indent=4, width=120, compact=True)
    #       )
    #   )
    ca=('xc', [
        'Snow Goose', 'Greater White-fronted Goose', 'Brant Goose', 'Cackling Goose', 'Canada Goose', 'Tundra Swan',
        'Egyptian Goose', 'Cinnamon Teal', 'Gadwall', 'American Wigeon', 'Mallard', 'Green-winged Teal', 'Redhead',
        'Surf Scoter', 'Bufflehead', 'Mountain Quail', 'California Quail', "Gambel's Quail", 'Sooty Grouse', 'Wild Turkey',
        'Red-throated Loon', 'Great Northern Loon', 'Pied-billed Grebe', 'Horned Grebe', 'Red-necked Grebe',
        'Western Grebe', "Clark's Grebe", 'Black-footed Albatross', 'Sooty Shearwater', 'Black-vented Shearwater',
        "Brandt's Cormorant", 'Pelagic Cormorant', 'Double-crested Cormorant', 'American Bittern', 'Least Bittern',
        'Great Blue Heron', 'Great Egret', 'Snowy Egret', 'Green Heron', 'Black-crowned Night Heron', 'White-faced Ibis',
        'Western Osprey', 'White-tailed Kite', 'Northern Harrier', "Cooper's Hawk", 'Common Black Hawk',
        'Red-shouldered Hawk', "Swainson's Hawk", 'Red-tailed Hawk', 'Black Rail', "Ridgway's Rail", 'Virginia Rail',
        'Sora', 'Common Gallinule', 'American Coot', 'Sandhill Crane', 'Black-necked Stilt', 'American Avocet',
        'Black Oystercatcher', 'Grey Plover', 'Pacific Golden Plover', 'Snowy Plover', 'Semipalmated Plover', 'Killdeer',
        'Whimbrel', 'Long-billed Curlew', 'Marbled Godwit', 'Black Turnstone', 'Surfbird', 'Dunlin', 'Rock Sandpiper',
        'Least Sandpiper', 'Western Sandpiper', 'Short-billed Dowitcher', 'Long-billed Dowitcher', 'Red-necked Phalarope',
        'Spotted Sandpiper', 'Solitary Sandpiper', 'Wandering Tattler', 'Greater Yellowlegs', 'Willet', 'Common Murre',
        'Marbled Murrelet', "Bonaparte's Gull", 'Laughing Gull', "Heermann's Gull", 'Mew Gull', 'Ring-billed Gull',
        'Western Gull', 'Yellow-footed Gull', 'California Gull', 'Glaucous-winged Gull', 'Least Tern', 'Gull-billed Tern',
        'Caspian Tern', 'Black Tern', "Forster's Tern", 'Royal Tern', 'Elegant Tern', 'Black Skimmer', 'Rock Dove',
        'Band-tailed Pigeon', 'Eurasian Collared Dove', 'African Collared Dove', 'Inca Dove', 'Common Ground Dove',
        'White-winged Dove', 'Mourning Dove', 'Greater Roadrunner', 'Yellow-billed Cuckoo', 'Western Barn Owl',
        'Flammulated Owl', 'Western Screech Owl', 'Great Horned Owl', 'Elf Owl', 'Burrowing Owl', 'Spotted Owl',
        'Long-eared Owl', 'Northern Saw-whet Owl', 'Lesser Nighthawk', 'Common Nighthawk', 'Common Poorwill',
        'Eastern Whip-poor-will', 'Mexican Whip-poor-will', "Vaux's Swift", 'White-throated Swift',
        'Black-chinned Hummingbird', "Anna's Hummingbird", "Costa's Hummingbird", 'Broad-tailed Hummingbird',
        "Allen's Hummingbird", 'Calliope Hummingbird', 'Belted Kingfisher', 'Acorn Woodpecker', 'Gila Woodpecker',
        "Williamson's Sapsucker", 'Red-breasted Sapsucker', 'Ladder-backed Woodpecker', "Nuttall's Woodpecker",
        'Downy Woodpecker', 'Hairy Woodpecker', 'White-headed Woodpecker', 'Black-backed Woodpecker', 'Northern Flicker',
        'Pileated Woodpecker', 'American Kestrel', 'Merlin', 'Peregrine Falcon', 'Cockatiel', 'Rose-ringed Parakeet',
        'Yellow-chevroned Parakeet', 'Red-crowned Amazon', 'Lilac-crowned Amazon', 'Yellow-headed Amazon',
        'Nanday Parakeet', 'Red-masked Parakeet', 'Olive-sided Flycatcher', 'Western Wood Pewee', 'Willow Flycatcher',
        'Least Flycatcher', "Hammond's Flycatcher", 'American Grey Flycatcher', 'American Dusky Flycatcher',
        'Pacific-slope Flycatcher', 'Black Phoebe', 'Eastern Phoebe', "Say's Phoebe", 'Vermilion Flycatcher',
        'Dusky-capped Flycatcher', 'Ash-throated Flycatcher', 'Brown-crested Flycatcher', 'Tropical Kingbird',
        "Couch's Kingbird", "Cassin's Kingbird", 'Thick-billed Kingbird', 'Western Kingbird', 'Loggerhead Shrike',
        'White-eyed Vireo', "Bell's Vireo", 'Grey Vireo', "Hutton's Vireo", "Cassin's Vireo", 'Plumbeous Vireo',
        'Warbling Vireo', 'Red-eyed Vireo', 'Yellow-green Vireo', 'Grey Jay', 'Black-throated Magpie-Jay', 'Pinyon Jay',
        "Steller's Jay", 'Island Scrub Jay', 'California Scrub Jay', "Woodhouse's Scrub Jay", 'Yellow-billed Magpie',
        "Clark's Nutcracker", 'American Crow', 'Northern Raven', 'Horned Lark', 'Northern Rough-winged Swallow',
        'Purple Martin', 'Tree Swallow', 'Violet-green Swallow', 'Barn Swallow', 'American Cliff Swallow',
        'Mountain Chickadee', 'Chestnut-backed Chickadee', 'Oak Titmouse', 'Juniper Titmouse', 'Verdin', 'American Bushtit',
        'Red-breasted Nuthatch', 'White-breasted Nuthatch', 'Pygmy Nuthatch', 'Brown Creeper', 'Rock Wren', 'Canyon Wren',
        'House Wren', 'Pacific Wren', 'Winter Wren', 'Marsh Wren', "Bewick's Wren", 'Cactus Wren', 'Blue-grey Gnatcatcher',
        'California Gnatcatcher', 'Black-tailed Gnatcatcher', 'American Dipper', 'Red-whiskered Bulbul',
        'Golden-crowned Kinglet', 'Ruby-crowned Kinglet', 'Dusky Warbler', 'Wrentit', 'Japanese White-eye',
        'Western Bluebird', 'Mountain Bluebird', "Townsend's Solitaire", "Swainson's Thrush", 'Hermit Thrush',
        'Wood Thrush', 'American Robin', 'Varied Thrush', 'Grey Catbird', 'Curve-billed Thrasher', "Bendire's Thrasher",
        'California Thrasher', "Le Conte's Thrasher", 'Crissal Thrasher', 'Sage Thrasher', 'Northern Mockingbird',
        'Common Starling', 'Olive-backed Pipit', 'Red-throated Pipit', 'Buff-bellied Pipit', 'Cedar Waxwing', 'Phainopepla',
        'Lapland Longspur', 'Worm-eating Warbler', 'Northern Waterthrush', 'Orange-crowned Warbler', "Lucy's Warbler",
        'Nashville Warbler', "MacGillivray's Warbler", 'Mourning Warbler', 'Common Yellowthroat', 'Hooded Warbler',
        'American Redstart', 'Northern Parula', 'Magnolia Warbler', 'Bay-breasted Warbler', 'Chestnut-sided Warbler',
        'Pine Warbler', 'Myrtle Warbler', 'Prairie Warbler', "Grace's Warbler", 'Black-throated Grey Warbler',
        "Townsend's Warbler", 'Hermit Warbler', "Wilson's Warbler", 'Painted Whitestart', "Cassin's Sparrow",
        'Grasshopper Sparrow', 'Chipping Sparrow', 'Clay-colored Sparrow', 'Black-chinned Sparrow', "Brewer's Sparrow",
        'Black-throated Sparrow', 'Lark Sparrow', 'Fox Sparrow', 'Dark-eyed Junco', 'White-crowned Sparrow',
        'Golden-crowned Sparrow', 'White-throated Sparrow', 'Sagebrush Sparrow', "Bell's Sparrow", 'Vesper Sparrow',
        'Savannah Sparrow', 'Song Sparrow', "Lincoln's Sparrow", "Abert's Towhee", 'California Towhee',
        'Rufous-crowned Sparrow', 'Green-tailed Towhee', 'Spotted Towhee', 'Yellow-breasted Chat', 'Summer Tanager',
        'Western Tanager', 'Northern Cardinal', 'Rose-breasted Grosbeak', 'Black-headed Grosbeak', 'Blue Grosbeak',
        'Lazuli Bunting', 'Indigo Bunting', 'Yellow-headed Blackbird', 'Western Meadowlark', 'Hooded Oriole',
        "Bullock's Oriole", "Scott's Oriole", 'Red-winged Blackbird', 'Tricolored Blackbird', 'Brown-headed Cowbird',
        "Brewer's Blackbird", 'Great-tailed Grackle', 'Evening Grosbeak', 'Pine Grosbeak', 'House Finch', 'Purple Finch',
        "Cassin's Finch", 'Red Crossbill', 'Pine Siskin', 'Lesser Goldfinch', "Lawrence's Goldfinch", 'American Goldfinch',
        'House Sparrow', 'Scaly-breasted Munia', 'Pin-tailed Whydah',
    ]),

    # US (sp=774): All xc com_name's that have ≥1 rec in US
    #   from notebooks import *
    #   import pprint
    #   (xc.metadata
    #       [lambda df: pd.notnull(df.species)]
    #       [lambda df: df.country == 'United States']
    #       .pipe(df_remove_unused_categories).com_name.sort_values()
    #       .pipe(puts, f=lambda s: len(s.unique()))
    #       .pipe(lambda s:
    #           pprint.pprint(s.unique().tolist(), indent=4, width=120, compact=True)
    #       )
    #   )
    us=('xc', [
        'Black-bellied Whistling Duck', 'Fulvous Whistling Duck', 'Emperor Goose', 'Snow Goose', "Ross's Goose",
        'Greater White-fronted Goose', 'Lesser White-fronted Goose', 'Tundra Bean Goose', 'Brant Goose', 'Cackling Goose',
        'Canada Goose', 'Nene', 'Mute Swan', 'Trumpeter Swan', 'Tundra Swan', 'Egyptian Goose', 'Wood Duck',
        'Blue-winged Teal', 'Cinnamon Teal', 'Northern Shoveler', 'Gadwall', 'Eurasian Wigeon', 'American Wigeon',
        'Laysan Duck', 'Hawaiian Duck', 'Mallard', 'American Black Duck', 'Mottled Duck', 'Northern Pintail',
        'Eurasian Teal', 'Green-winged Teal', 'Canvasback', 'Redhead', 'Ring-necked Duck', 'Greater Scaup', 'Lesser Scaup',
        "Steller's Eider", 'Spectacled Eider', 'King Eider', 'Common Eider', 'Harlequin Duck', 'Surf Scoter',
        'Black Scoter', 'Long-tailed Duck', 'Bufflehead', 'Common Goldeneye', "Barrow's Goldeneye", 'Hooded Merganser',
        'Common Merganser', 'Red-breasted Merganser', 'Ruddy Duck', 'Plain Chachalaca', 'Helmeted Guineafowl',
        'Mountain Quail', 'Northern Bobwhite', 'Scaled Quail', 'California Quail', "Gambel's Quail", 'Montezuma Quail',
        'Indian Peafowl', 'Chukar Partridge', 'Himalayan Snowcock', "Erckel's Francolin", 'Black Francolin',
        'Grey Francolin', 'Common Pheasant', 'Kalij Pheasant', 'Grey Partridge', 'Ruffed Grouse', 'Sage Grouse',
        'Gunnison Grouse', 'Spruce Grouse', 'Willow Ptarmigan', 'Rock Ptarmigan', 'White-tailed Ptarmigan', 'Dusky Grouse',
        'Sooty Grouse', 'Sharp-tailed Grouse', 'Greater Prairie Chicken', 'Lesser Prairie Chicken', 'Wild Turkey',
        'Red-throated Loon', 'Pacific Loon', 'Great Northern Loon', 'Yellow-billed Loon', 'Least Grebe',
        'Pied-billed Grebe', 'Horned Grebe', 'Red-necked Grebe', 'Black-necked Grebe', 'Western Grebe', "Clark's Grebe",
        'Laysan Albatross', 'Black-footed Albatross', 'Northern Fulmar', 'Hawaiian Petrel', 'Bonin Petrel',
        'Wedge-tailed Shearwater', 'Sooty Shearwater', "Newell's Shearwater", 'Black-vented Shearwater',
        'Red-tailed Tropicbird', 'Wood Stork', 'Great Frigatebird', 'Red-footed Booby', "Brandt's Cormorant",
        'Red-faced Cormorant', 'Pelagic Cormorant', 'Neotropic Cormorant', 'Double-crested Cormorant', 'Anhinga',
        'American White Pelican', 'Brown Pelican', 'American Bittern', 'Least Bittern', 'Great Blue Heron', 'Great Egret',
        'Snowy Egret', 'Little Blue Heron', 'Tricolored Heron', 'Reddish Egret', 'Western Cattle Egret', 'Green Heron',
        'Black-crowned Night Heron', 'Yellow-crowned Night Heron', 'American White Ibis', 'Glossy Ibis', 'White-faced Ibis',
        'Roseate Spoonbill', 'Black Vulture', 'Turkey Vulture', 'Western Osprey', 'White-tailed Kite',
        'Swallow-tailed Kite', 'Golden Eagle', 'Snail Kite', 'Mississippi Kite', 'Northern Harrier', 'Sharp-shinned Hawk',
        "Cooper's Hawk", 'Northern Goshawk', 'Bald Eagle', 'Common Black Hawk', "Harris's Hawk", 'White-tailed Hawk',
        'Grey Hawk', 'Red-shouldered Hawk', 'Broad-winged Hawk', 'Hawaiian Hawk', "Swainson's Hawk", 'Zone-tailed Hawk',
        'Red-tailed Hawk', 'Rough-legged Buzzard', 'Ferruginous Hawk', 'Yellow Rail', 'Black Rail', "Ridgway's Rail",
        'King Rail', 'Clapper Rail', 'Virginia Rail', 'Rufous-necked Wood Rail', 'Sora', 'Purple Gallinule',
        'Purple Swamphen', 'Common Gallinule', 'Hawaiian Coot', 'American Coot', 'Limpkin', 'Sandhill Crane',
        'Whooping Crane', 'Red-crowned Crane', 'Black-necked Stilt', 'American Avocet', 'American Oystercatcher',
        'Black Oystercatcher', 'Grey Plover', 'American Golden Plover', 'Pacific Golden Plover', 'Snowy Plover',
        "Wilson's Plover", 'Semipalmated Plover', 'Piping Plover', 'Killdeer', 'Mountain Plover', 'Northern Jacana',
        'Upland Sandpiper', 'Bristle-thighed Curlew', 'Whimbrel', 'Long-billed Curlew', 'Bar-tailed Godwit',
        'Hudsonian Godwit', 'Marbled Godwit', 'Ruddy Turnstone', 'Black Turnstone', 'Red Knot', 'Surfbird',
        'Sharp-tailed Sandpiper', 'Stilt Sandpiper', 'Red-necked Stint', 'Sanderling', 'Dunlin', 'Rock Sandpiper',
        'Purple Sandpiper', "Baird's Sandpiper", 'Least Sandpiper', 'White-rumped Sandpiper', 'Pectoral Sandpiper',
        'Semipalmated Sandpiper', 'Western Sandpiper', 'Short-billed Dowitcher', 'Long-billed Dowitcher',
        'American Woodcock', "Wilson's Snipe", 'Pin-tailed Snipe', "Wilson's Phalarope", 'Red-necked Phalarope',
        'Red Phalarope', 'Spotted Sandpiper', 'Solitary Sandpiper', 'Grey-tailed Tattler', 'Wandering Tattler',
        'Greater Yellowlegs', 'Willet', 'Lesser Yellowlegs', 'Wood Sandpiper', 'Pomarine Skua', 'Parasitic Jaeger',
        'Long-tailed Jaeger', 'Common Murre', 'Thick-billed Murre', 'Razorbill', 'Pigeon Guillemot', 'Marbled Murrelet',
        'Ancient Murrelet', 'Parakeet Auklet', 'Least Auklet', 'Whiskered Auklet', 'Crested Auklet', 'Horned Puffin',
        'Black-legged Kittiwake', 'Red-legged Kittiwake', "Sabine's Gull", "Bonaparte's Gull", 'Little Gull', "Ross's Gull",
        'Laughing Gull', "Franklin's Gull", "Heermann's Gull", 'Mew Gull', 'Ring-billed Gull', 'Western Gull',
        'Yellow-footed Gull', 'California Gull', 'Lesser Black-backed Gull', 'Slaty-backed Gull', 'Glaucous-winged Gull',
        'Glaucous Gull', 'Great Black-backed Gull', 'Brown Noddy', 'Black Noddy', 'White Tern', 'Sooty Tern',
        'Aleutian Tern', 'Least Tern', 'Gull-billed Tern', 'Caspian Tern', 'Black Tern', 'Roseate Tern', 'Common Tern',
        'Arctic Tern', "Forster's Tern", 'Royal Tern', 'Elegant Tern', 'Black Skimmer', 'Rock Dove', 'White-crowned Pigeon',
        'Red-billed Pigeon', 'Band-tailed Pigeon', 'Eurasian Collared Dove', 'African Collared Dove', 'Spotted Dove',
        'Zebra Dove', 'Inca Dove', 'Common Ground Dove', 'White-tipped Dove', 'White-winged Dove', 'Mourning Dove',
        'Mariana Fruit Dove', 'Pacific Imperial Pigeon', 'Smooth-billed Ani', 'Groove-billed Ani', 'Greater Roadrunner',
        'Yellow-billed Cuckoo', 'Mangrove Cuckoo', 'Black-billed Cuckoo', 'Pacific Long-tailed Cuckoo', 'Western Barn Owl',
        'Flammulated Owl', 'Western Screech Owl', 'Eastern Screech Owl', 'Whiskered Screech Owl', 'Great Horned Owl',
        'Northern Hawk-Owl', 'Mountain Pygmy Owl', 'Ferruginous Pygmy Owl', 'Elf Owl', 'Burrowing Owl', 'Spotted Owl',
        'Northern Barred Owl', 'Great Grey Owl', 'Long-eared Owl', 'Short-eared Owl', 'Boreal Owl', 'Northern Saw-whet Owl',
        'Lesser Nighthawk', 'Common Nighthawk', 'Antillean Nighthawk', 'Pauraque', 'Common Poorwill', "Chuck-will's-widow",
        'Buff-collared Nightjar', 'Eastern Whip-poor-will', 'Mexican Whip-poor-will', 'American Black Swift',
        'Chimney Swift', "Vaux's Swift", 'White-throated Swift', 'Magnificent Hummingbird', 'Plain-capped Starthroat',
        'Blue-throated Mountaingem', 'Lucifer Sheartail', 'Ruby-throated Hummingbird', 'Black-chinned Hummingbird',
        "Anna's Hummingbird", "Costa's Hummingbird", 'Broad-tailed Hummingbird', 'Rufous Hummingbird',
        "Allen's Hummingbird", 'Calliope Hummingbird', 'Broad-billed Hummingbird', 'Berylline Hummingbird',
        'Buff-bellied Hummingbird', 'Violet-crowned Hummingbird', 'Elegant Trogon', 'Collared Kingfisher',
        'Ringed Kingfisher', 'Belted Kingfisher', 'Green Kingfisher', "Lewis's Woodpecker", 'Red-headed Woodpecker',
        'Acorn Woodpecker', 'Gila Woodpecker', 'Golden-fronted Woodpecker', 'Red-bellied Woodpecker',
        "Williamson's Sapsucker", 'Yellow-bellied Sapsucker', 'Red-naped Sapsucker', 'Red-breasted Sapsucker',
        'Ladder-backed Woodpecker', "Nuttall's Woodpecker", 'Downy Woodpecker', 'Hairy Woodpecker', 'Arizona Woodpecker',
        'Red-cockaded Woodpecker', 'White-headed Woodpecker', 'American Three-toed Woodpecker', 'Black-backed Woodpecker',
        'Northern Flicker', 'Gilded Flicker', 'Pileated Woodpecker', 'Northern Crested Caracara', 'American Kestrel',
        'Merlin', 'Gyrfalcon', 'Peregrine Falcon', 'Prairie Falcon', 'Cockatiel', 'Rose-ringed Parakeet', 'Budgerigar',
        'Blue-crowned Lorikeet', 'Rosy-faced Lovebird', 'Monk Parakeet', 'White-winged Parakeet',
        'Yellow-chevroned Parakeet', 'Red-crowned Amazon', 'Lilac-crowned Amazon', 'Yellow-headed Amazon',
        'Orange-winged Amazon', 'Nanday Parakeet', 'Blue-and-yellow Macaw', 'Blue-crowned Parakeet', 'Green Parakeet',
        'Mitred Parakeet', 'Red-masked Parakeet', 'Northern Beardless Tyrannulet', 'Northern Tufted Flycatcher',
        'Olive-sided Flycatcher', 'Greater Pewee', 'Western Wood Pewee', 'Eastern Wood Pewee', 'Yellow-bellied Flycatcher',
        'Acadian Flycatcher', 'Alder Flycatcher', 'Willow Flycatcher', 'Least Flycatcher', "Hammond's Flycatcher",
        'American Grey Flycatcher', 'American Dusky Flycatcher', 'Pine Flycatcher', 'Pacific-slope Flycatcher',
        'Cordilleran Flycatcher', 'Buff-breasted Flycatcher', 'Black Phoebe', 'Eastern Phoebe', "Say's Phoebe",
        'Vermilion Flycatcher', 'Dusky-capped Flycatcher', 'Ash-throated Flycatcher', "Nutting's Flycatcher",
        'Great Crested Flycatcher', 'Brown-crested Flycatcher', "La Sagra's Flycatcher", 'Great Kiskadee',
        'Sulphur-bellied Flycatcher', 'Tropical Kingbird', "Couch's Kingbird", "Cassin's Kingbird", 'Thick-billed Kingbird',
        'Western Kingbird', 'Eastern Kingbird', 'Grey Kingbird', 'Scissor-tailed Flycatcher', 'Rose-throated Becard',
        'Micronesian Myzomela', 'Cardinal Myzomela', 'Wattled Honeyeater', 'Loggerhead Shrike', 'Great Grey Shrike',
        'Black-capped Vireo', 'White-eyed Vireo', "Bell's Vireo", 'Grey Vireo', "Hutton's Vireo", 'Yellow-throated Vireo',
        "Cassin's Vireo", 'Blue-headed Vireo', 'Plumbeous Vireo', 'Philadelphia Vireo', 'Warbling Vireo', 'Red-eyed Vireo',
        'Yellow-green Vireo', 'Black-whiskered Vireo', 'Hawaii Elepaio', 'Kauai Elepaio', 'Oahu Elepaio', 'Fiji Shrikebill',
        'Grey Jay', 'Black-throated Magpie-Jay', 'Brown Jay', 'Green Jay', 'Pinyon Jay', "Steller's Jay", 'Blue Jay',
        'Florida Scrub Jay', 'Island Scrub Jay', 'California Scrub Jay', "Woodhouse's Scrub Jay", 'Mexican Jay',
        'Black-billed Magpie', 'Yellow-billed Magpie', "Clark's Nutcracker", 'Mariana Crow', 'American Crow',
        'Northwestern Crow', 'Tamaulipas Crow', 'Fish Crow', 'Chihuahuan Raven', 'Northern Raven', 'Horned Lark',
        'Eurasian Skylark', 'Northern Rough-winged Swallow', 'Purple Martin', 'Tree Swallow', 'Violet-green Swallow',
        'Sand Martin', 'Barn Swallow', 'American Cliff Swallow', 'Cave Swallow', 'Carolina Chickadee',
        'Black-capped Chickadee', 'Mountain Chickadee', 'Mexican Chickadee', 'Chestnut-backed Chickadee',
        'Boreal Chickadee', 'Bridled Titmouse', 'Oak Titmouse', 'Juniper Titmouse', 'Tufted Titmouse',
        'Black-crested Titmouse', 'Verdin', 'American Bushtit', 'Red-breasted Nuthatch', 'White-breasted Nuthatch',
        'Pygmy Nuthatch', 'Brown-headed Nuthatch', 'Brown Creeper', 'Rock Wren', 'Canyon Wren', 'House Wren',
        'Pacific Wren', 'Winter Wren', 'Sedge Wren', 'Marsh Wren', 'Carolina Wren', "Bewick's Wren", 'Cactus Wren',
        'Sinaloa Wren', 'Blue-grey Gnatcatcher', 'California Gnatcatcher', 'Black-tailed Gnatcatcher',
        'Black-capped Gnatcatcher', 'American Dipper', 'Red-vented Bulbul', 'Red-whiskered Bulbul',
        'Golden-crowned Kinglet', 'Ruby-crowned Kinglet', 'Japanese Bush Warbler', 'Dusky Warbler', 'Arctic Warbler',
        'Saipan Reed Warbler', 'Millerbird', 'Wrentit', 'Japanese White-eye', 'Rota White-eye', 'Chinese Hwamei',
        'Red-billed Leiothrix', 'White-rumped Shama', 'Bluethroat', 'Northern Wheatear', 'Eastern Bluebird',
        'Western Bluebird', 'Mountain Bluebird', "Townsend's Solitaire", 'Brown-backed Solitaire', 'Omao', 'Puaiohi',
        'Orange-billed Nightingale-Thrush', 'Veery', 'Grey-cheeked Thrush', "Bicknell's Thrush", "Swainson's Thrush",
        'Hermit Thrush', 'Wood Thrush', 'Clay-colored Thrush', 'Rufous-backed Thrush', 'American Robin', 'Varied Thrush',
        'Grey Catbird', 'Curve-billed Thrasher', 'Brown Thrasher', 'Long-billed Thrasher', "Bendire's Thrasher",
        'California Thrasher', "Le Conte's Thrasher", 'Crissal Thrasher', 'Sage Thrasher', 'Northern Mockingbird',
        'Polynesian Starling', 'Samoan Starling', 'Common Hill Myna', 'Common Starling', 'Common Myna',
        'Eastern Yellow Wagtail', 'White Wagtail', 'Olive-backed Pipit', 'Red-throated Pipit', 'Buff-bellied Pipit',
        "Sprague's Pipit", 'Bohemian Waxwing', 'Cedar Waxwing', 'Phainopepla', 'Olive Warbler', 'Lapland Longspur',
        'Chestnut-collared Longspur', "Smith's Longspur", "McCown's Longspur", 'Snow Bunting', "McKay's Bunting",
        'Ovenbird', 'Worm-eating Warbler', 'Louisiana Waterthrush', 'Northern Waterthrush', 'Golden-winged Warbler',
        'Blue-winged Warbler', 'Black-and-white Warbler', 'Prothonotary Warbler', "Swainson's Warbler",
        'Crescent-chested Warbler', 'Tennessee Warbler', 'Orange-crowned Warbler', 'Colima Warbler', "Lucy's Warbler",
        'Nashville Warbler', "Virginia's Warbler", 'Connecticut Warbler', 'Grey-crowned Yellowthroat',
        "MacGillivray's Warbler", 'Mourning Warbler', 'Kentucky Warbler', 'Common Yellowthroat', 'Hooded Warbler',
        'American Redstart', "Kirtland's Warbler", 'Cape May Warbler', 'Cerulean Warbler', 'Northern Parula',
        'Tropical Parula', 'Magnolia Warbler', 'Bay-breasted Warbler', 'Blackburnian Warbler', 'Mangrove Warbler',
        'Chestnut-sided Warbler', 'Blackpoll Warbler', 'Black-throated Blue Warbler', 'Palm Warbler', 'Pine Warbler',
        'Myrtle Warbler', 'Yellow-throated Warbler', 'Prairie Warbler', "Grace's Warbler", 'Black-throated Grey Warbler',
        "Townsend's Warbler", 'Hermit Warbler', 'Golden-cheeked Warbler', 'Black-throated Green Warbler',
        'Rufous-capped Warbler', 'Golden-crowned Warbler', 'Canada Warbler', "Wilson's Warbler", 'Red-faced Warbler',
        'Painted Whitestart', 'Slate-throated Whitestart', 'Red-crested Cardinal', 'Saffron Finch',
        'White-collared Seedeater', 'Bananaquit', 'Rufous-winged Sparrow', "Botteri's Sparrow", "Cassin's Sparrow",
        "Bachman's Sparrow", 'Grasshopper Sparrow', "Baird's Sparrow", "Henslow's Sparrow", "Le Conte's Sparrow",
        "Nelson's Sparrow", 'Saltmarsh Sparrow', 'Seaside Sparrow', 'Olive Sparrow', 'American Tree Sparrow',
        'Chipping Sparrow', 'Clay-colored Sparrow', 'Black-chinned Sparrow', 'Field Sparrow', "Brewer's Sparrow",
        'Black-throated Sparrow', 'Five-striped Sparrow', 'Lark Sparrow', 'Lark Bunting', 'Fox Sparrow', 'Dark-eyed Junco',
        'Yellow-eyed Junco', 'White-crowned Sparrow', 'Golden-crowned Sparrow', "Harris's Sparrow",
        'White-throated Sparrow', 'Sagebrush Sparrow', "Bell's Sparrow", 'Vesper Sparrow', 'Savannah Sparrow',
        'Song Sparrow', "Lincoln's Sparrow", 'Swamp Sparrow', 'Canyon Towhee', "Abert's Towhee", 'California Towhee',
        'Rufous-crowned Sparrow', 'Green-tailed Towhee', 'Spotted Towhee', 'Eastern Towhee', 'Western Spindalis',
        'Yellow-breasted Chat', 'Hepatic Tanager', 'Summer Tanager', 'Scarlet Tanager', 'Western Tanager',
        'Flame-colored Tanager', 'Crimson-collared Grosbeak', 'Northern Cardinal', 'Pyrrhuloxia', 'Rose-breasted Grosbeak',
        'Black-headed Grosbeak', 'Blue Grosbeak', 'Lazuli Bunting', 'Indigo Bunting', 'Varied Bunting', 'Painted Bunting',
        'Dickcissel', 'Yellow-headed Blackbird', 'Bobolink', 'Western Meadowlark', 'Eastern Meadowlark',
        'Puerto Rican Oriole', 'Black-vented Oriole', 'Orchard Oriole', 'Hooded Oriole', 'Streak-backed Oriole',
        "Bullock's Oriole", 'Spot-breasted Oriole', 'Altamira Oriole', "Audubon's Oriole", 'Baltimore Oriole',
        "Scott's Oriole", 'Red-winged Blackbird', 'Tricolored Blackbird', 'Shiny Cowbird', 'Bronzed Cowbird',
        'Brown-headed Cowbird', 'Rusty Blackbird', "Brewer's Blackbird", 'Common Grackle', 'Boat-tailed Grackle',
        'Great-tailed Grackle', 'Evening Grosbeak', 'Akikiki', 'Maui Alauahio', 'Palila', 'Nihoa Finch', 'Akohekohe',
        'Apapane', 'Iiwi', 'Maui Parrotbill', 'Akiapolaau', 'Anianiau', 'Hawaii Amakihi', 'Oahu Amakihi', 'Kauai Amakihi',
        'Hawaii Creeper', 'Akekee', 'Akepa', 'Pine Grosbeak', 'Grey-crowned Rosy Finch', 'Black Rosy Finch',
        'Brown-capped Rosy Finch', 'House Finch', 'Purple Finch', "Cassin's Finch", 'Yellow-fronted Canary',
        'Common Redpoll', 'Arctic Redpoll', 'Red Crossbill', 'Two-barred Crossbill', 'Pine Siskin', 'Lesser Goldfinch',
        "Lawrence's Goldfinch", 'American Goldfinch', 'House Sparrow', 'Eurasian Tree Sparrow', 'Common Waxbill',
        'Red Avadavat', 'Bronze Mannikin', 'African Silverbill', 'Scaly-breasted Munia', 'Chestnut Munia', 'Java Sparrow',
        'Pin-tailed Whydah',
    ]),

    # CA: All ebird com_name's with observations in the last 10y
    #   '''
    #   http --follow 'https://ebird.org/barchart?byr=2008&r=US-CA' \
    #       | pup '[data-species-code] json{}' \
    #       | jq 'map({species_code: ."data-species-code", com_name: .text})' \
    #       > /tmp/US-CA.json
    #   '''
    #   import html
    #   (pd.read_json('/tmp/US-CA.json')
    #       .applymap(html.unescape)  # Decode html entities leftover from pup
    #       .com_name
    #       .pipe(puts, f=lambda s: len(s.unique()))
    #       .pipe(lambda s:
    #           pprint.pprint(s.unique().tolist(), indent=8, width=120, compact=True)
    #       )
    #   )
    ca_ebird=('ebird', [
        'Black-bellied Whistling-Duck', 'Fulvous Whistling-Duck', 'Emperor Goose', 'Snow Goose', "Ross's Goose",
        'Greater White-fronted Goose', 'Taiga Bean-Goose', 'Tundra Bean-Goose', 'Brant', 'Cackling Goose',
        'Canada Goose', 'Mute Swan', 'Trumpeter Swan', 'Tundra Swan', 'Whooper Swan', 'Egyptian Goose', 'Muscovy Duck',
        'Wood Duck', 'Mandarin Duck', 'Garganey', 'Blue-winged Teal', 'Cinnamon Teal', 'Northern Shoveler', 'Gadwall',
        'Falcated Duck', 'Eurasian Wigeon', 'American Wigeon', 'Mallard', 'Mexican Duck', 'Northern Pintail',
        'Green-winged Teal', 'Canvasback', 'Redhead', 'Common Pochard', 'Ring-necked Duck', 'Tufted Duck',
        'Greater Scaup', 'Lesser Scaup', 'King Eider', 'Common Eider', 'Harlequin Duck', 'Surf Scoter',
        'White-winged Scoter', 'Common Scoter', 'Black Scoter', 'Long-tailed Duck', 'Bufflehead', 'Common Goldeneye',
        "Barrow's Goldeneye", 'Hooded Merganser', 'Common Merganser', 'Red-breasted Merganser', 'Ruddy Duck',
        'Mountain Quail', 'California Quail', "Gambel's Quail", 'Indian Peafowl', 'Chukar', 'Ring-necked Pheasant',
        'Ruffed Grouse', 'Greater Sage-Grouse', 'White-tailed Ptarmigan', 'Sooty Grouse', 'Wild Turkey',
        'Pied-billed Grebe', 'Horned Grebe', 'Red-necked Grebe', 'Eared Grebe', 'Western Grebe', "Clark's Grebe",
        'Rock Pigeon', 'Band-tailed Pigeon', 'Eurasian Collared-Dove', 'African Collared-Dove', 'Spotted Dove',
        'Inca Dove', 'Common Ground-Dove', 'Ruddy Ground-Dove', 'White-winged Dove', 'Mourning Dove',
        'Groove-billed Ani', 'Greater Roadrunner', 'Yellow-billed Cuckoo', 'Black-billed Cuckoo', 'Common Cuckoo',
        'Lesser Nighthawk', 'Common Nighthawk', 'Common Poorwill', 'Eastern Whip-poor-will', 'Mexican Whip-poor-will',
        'Black Swift', 'Chimney Swift', "Vaux's Swift", 'Common Swift', 'White-throated Swift',
        'Blue-throated Hummingbird', 'Ruby-throated Hummingbird', 'Black-chinned Hummingbird', "Anna's Hummingbird",
        "Costa's Hummingbird", 'Broad-tailed Hummingbird', 'Rufous Hummingbird', "Allen's Hummingbird",
        'Calliope Hummingbird', 'Broad-billed Hummingbird', 'Violet-crowned Hummingbird', "Ridgway's Rail",
        'Virginia Rail', 'Sora', 'Common Gallinule', 'American Coot', 'Purple Gallinule', 'Yellow Rail', 'Black Rail',
        'Sandhill Crane', 'Common Crane', 'Black-necked Stilt', 'American Avocet', 'American Oystercatcher',
        'Black Oystercatcher', 'Black-bellied Plover', 'American Golden-Plover', 'Pacific Golden-Plover',
        'Lesser Sand-Plover', 'Snowy Plover', "Wilson's Plover", 'Common Ringed Plover', 'Semipalmated Plover',
        'Killdeer', 'Mountain Plover', 'Upland Sandpiper', 'Whimbrel', 'Long-billed Curlew', 'Bar-tailed Godwit',
        'Hudsonian Godwit', 'Marbled Godwit', 'Ruddy Turnstone', 'Black Turnstone', 'Red Knot', 'Surfbird', 'Ruff',
        'Sharp-tailed Sandpiper', 'Stilt Sandpiper', 'Curlew Sandpiper', 'Red-necked Stint', 'Sanderling', 'Dunlin',
        'Rock Sandpiper', 'Purple Sandpiper', "Baird's Sandpiper", 'Little Stint', 'Least Sandpiper',
        'White-rumped Sandpiper', 'Buff-breasted Sandpiper', 'Pectoral Sandpiper', 'Semipalmated Sandpiper',
        'Western Sandpiper', 'Short-billed Dowitcher', 'Long-billed Dowitcher', 'American Woodcock', 'Common Snipe',
        "Wilson's Snipe", "Wilson's Phalarope", 'Red-necked Phalarope', 'Red Phalarope', 'Spotted Sandpiper',
        'Solitary Sandpiper', 'Wandering Tattler', 'Greater Yellowlegs', 'Willet', 'Lesser Yellowlegs',
        'Marsh Sandpiper', 'Wood Sandpiper', 'South Polar Skua', 'Pomarine Jaeger', 'Parasitic Jaeger',
        'Long-tailed Jaeger', 'Common Murre', 'Thick-billed Murre', 'Pigeon Guillemot', 'Long-billed Murrelet',
        'Marbled Murrelet', "Scripps's Murrelet", 'Guadalupe Murrelet', "Craveri's Murrelet", 'Ancient Murrelet',
        "Cassin's Auklet", 'Parakeet Auklet', 'Rhinoceros Auklet', 'Horned Puffin', 'Tufted Puffin',
        'Swallow-tailed Gull', 'Black-legged Kittiwake', 'Ivory Gull', "Sabine's Gull", "Bonaparte's Gull",
        'Black-headed Gull', 'Little Gull', "Ross's Gull", 'Laughing Gull', "Franklin's Gull", 'Black-tailed Gull',
        "Heermann's Gull", 'Mew Gull', 'Ring-billed Gull', 'Western Gull', 'Yellow-footed Gull', 'California Gull',
        'Herring Gull', 'Iceland Gull', 'Lesser Black-backed Gull', 'Slaty-backed Gull', 'Glaucous-winged Gull',
        'Glaucous Gull', 'Great Black-backed Gull', 'Kelp Gull', 'Sooty Tern', 'Bridled Tern', 'Least Tern',
        'Gull-billed Tern', 'Caspian Tern', 'Black Tern', 'Common Tern', 'Arctic Tern', "Forster's Tern", 'Royal Tern',
        'Elegant Tern', 'Black Skimmer', 'Red-billed Tropicbird', 'Red-tailed Tropicbird', 'Red-throated Loon',
        'Arctic Loon', 'Pacific Loon', 'Common Loon', 'Yellow-billed Loon', "Salvin's Albatross", 'Laysan Albatross',
        'Black-footed Albatross', 'Short-tailed Albatross', "Wilson's Storm-Petrel", 'Fork-tailed Storm-Petrel',
        "Leach's Storm-Petrel", "Townsend's Storm-Petrel", "Leach's/Townsend's Storm-Petrel (dark-rumped)",
        "Leach's/Townsend's Storm-Petrel (white-rumped)", 'Ashy Storm-Petrel', 'Band-rumped Storm-Petrel',
        'Wedge-rumped Storm-Petrel', 'Black Storm-Petrel', 'Least Storm-Petrel', 'Northern Fulmar', 'Gray-faced Petrel',
        'Kermadec Petrel', "Murphy's Petrel", 'Mottled Petrel', 'Hawaiian Petrel', "Cook's Petrel",
        "Stejneger's Petrel", "Jouanin's Petrel", 'White-chinned Petrel', "Cory's Shearwater", 'Pink-footed Shearwater',
        'Flesh-footed Shearwater', 'Great Shearwater', 'Wedge-tailed Shearwater', "Buller's Shearwater",
        'Sooty Shearwater', 'Short-tailed Shearwater', 'Manx Shearwater', 'Black-vented Shearwater', 'Wood Stork',
        'Magnificent Frigatebird', 'Great Frigatebird', 'Masked Booby', 'Nazca Booby', 'Blue-footed Booby',
        'Brown Booby', 'Red-footed Booby', 'Northern Gannet', "Brandt's Cormorant", 'Pelagic Cormorant',
        'Neotropic Cormorant', 'Double-crested Cormorant', 'American White Pelican', 'Brown Pelican',
        'American Bittern', 'Least Bittern', 'Great Blue Heron', 'Great Egret', 'Snowy Egret', 'Little Blue Heron',
        'Tricolored Heron', 'Reddish Egret', 'Cattle Egret', 'Green Heron', 'Black-crowned Night-Heron',
        'Yellow-crowned Night-Heron', 'White Ibis', 'Glossy Ibis', 'White-faced Ibis', 'Roseate Spoonbill',
        'California Condor', 'Black Vulture', 'Turkey Vulture', 'Osprey', 'White-tailed Kite', 'Swallow-tailed Kite',
        'Golden Eagle', 'Mississippi Kite', 'Northern Harrier', 'Sharp-shinned Hawk', "Cooper's Hawk",
        'Northern Goshawk', 'Bald Eagle', 'Common Black Hawk', "Harris's Hawk", 'Gray Hawk', 'Red-shouldered Hawk',
        'Broad-winged Hawk', "Swainson's Hawk", 'Zone-tailed Hawk', 'Red-tailed Hawk', 'Rough-legged Hawk',
        'Ferruginous Hawk', 'Barn Owl', 'Flammulated Owl', 'Western Screech-Owl', 'Great Horned Owl', 'Snowy Owl',
        'Northern Pygmy-Owl', 'Elf Owl', 'Burrowing Owl', 'Spotted Owl', 'Barred Owl', 'Great Gray Owl',
        'Long-eared Owl', 'Short-eared Owl', 'Northern Saw-whet Owl', 'Belted Kingfisher', 'Eurasian Wryneck',
        "Williamson's Sapsucker", 'Yellow-bellied Sapsucker', 'Red-naped Sapsucker', 'Red-breasted Sapsucker',
        "Lewis's Woodpecker", 'Acorn Woodpecker', 'Gila Woodpecker', 'Black-backed Woodpecker', 'Downy Woodpecker',
        "Nuttall's Woodpecker", 'Ladder-backed Woodpecker', 'Hairy Woodpecker', 'White-headed Woodpecker',
        'Pileated Woodpecker', 'Northern Flicker', 'Gilded Flicker', 'Crested Caracara', 'American Kestrel', 'Merlin',
        'Gyrfalcon', 'Peregrine Falcon', 'Prairie Falcon', 'Rose-ringed Parakeet', 'Monk Parakeet',
        'White-winged Parakeet', 'Yellow-chevroned Parakeet', 'Red-crowned Parrot', 'Lilac-crowned Parrot',
        'Red-lored Parrot', 'Yellow-headed Parrot', 'Yellow-crowned Parrot', 'Turquoise-fronted Parrot',
        'White-fronted Parrot', 'Nanday Parakeet', 'Blue-crowned Parakeet', 'Mitred Parakeet', 'Red-masked Parakeet',
        'Olive-sided Flycatcher', 'Greater Pewee', 'Western Wood-Pewee', 'Eastern Wood-Pewee',
        'Yellow-bellied Flycatcher', 'Alder Flycatcher', 'Willow Flycatcher', 'Least Flycatcher',
        "Hammond's Flycatcher", 'Gray Flycatcher', 'Dusky Flycatcher', 'Pacific-slope Flycatcher',
        'Cordilleran Flycatcher', 'Buff-breasted Flycatcher', 'Black Phoebe', 'Eastern Phoebe', "Say's Phoebe",
        'Vermilion Flycatcher', 'Dusky-capped Flycatcher', 'Ash-throated Flycatcher', 'Great Crested Flycatcher',
        'Brown-crested Flycatcher', 'Sulphur-bellied Flycatcher', 'Tropical Kingbird', "Couch's Kingbird",
        "Cassin's Kingbird", 'Thick-billed Kingbird', 'Western Kingbird', 'Eastern Kingbird',
        'Scissor-tailed Flycatcher', 'Brown Shrike', 'Loggerhead Shrike', 'Northern Shrike', 'White-eyed Vireo',
        "Bell's Vireo", 'Gray Vireo', "Hutton's Vireo", 'Yellow-throated Vireo', "Cassin's Vireo", 'Blue-headed Vireo',
        'Plumbeous Vireo', 'Philadelphia Vireo', 'Warbling Vireo', 'Red-eyed Vireo', 'Yellow-green Vireo', 'Canada Jay',
        'Black-throated Magpie-Jay', 'Pinyon Jay', "Steller's Jay", 'Blue Jay', 'Island Scrub-Jay',
        'California Scrub-Jay', "Woodhouse's Scrub-Jay", 'Black-billed Magpie', 'Yellow-billed Magpie',
        "Clark's Nutcracker", 'American Crow', 'Common Raven', 'Horned Lark', 'Eurasian Skylark',
        'Northern Rough-winged Swallow', 'Purple Martin', 'Tree Swallow', 'Violet-green Swallow', 'Bank Swallow',
        'Barn Swallow', 'Cliff Swallow', 'Cave Swallow', 'Black-capped Chickadee', 'Mountain Chickadee',
        'Chestnut-backed Chickadee', 'Oak Titmouse', 'Juniper Titmouse', 'Verdin', 'Bushtit', 'Red-breasted Nuthatch',
        'White-breasted Nuthatch', 'Pygmy Nuthatch', 'Brown Creeper', 'Rock Wren', 'Canyon Wren', 'House Wren',
        'Pacific Wren', 'Winter Wren', 'Sedge Wren', 'Marsh Wren', "Bewick's Wren", 'Cactus Wren',
        'Blue-gray Gnatcatcher', 'California Gnatcatcher', 'Black-tailed Gnatcatcher', 'American Dipper',
        'Red-whiskered Bulbul', 'Golden-crowned Kinglet', 'Ruby-crowned Kinglet', 'Dusky Warbler', 'Arctic Warbler',
        'Wrentit', 'Japanese White-eye', 'Bluethroat', 'Red-flanked Bluetail', 'Northern Wheatear', 'Western Bluebird',
        'Mountain Bluebird', "Townsend's Solitaire", 'Varied Thrush', 'Veery', 'Gray-cheeked Thrush',
        "Swainson's Thrush", 'Hermit Thrush', 'Wood Thrush', 'American Robin', 'Rufous-backed Robin', 'Gray Catbird',
        'Curve-billed Thrasher', 'Brown Thrasher', "Bendire's Thrasher", 'California Thrasher', "LeConte's Thrasher",
        'Crissal Thrasher', 'Sage Thrasher', 'Northern Mockingbird', 'European Starling', 'Eastern Yellow Wagtail',
        'Citrine Wagtail', 'White Wagtail', 'Olive-backed Pipit', 'Red-throated Pipit', 'American Pipit',
        "Sprague's Pipit", 'Bohemian Waxwing', 'Cedar Waxwing', 'Phainopepla', 'Brambling', 'Evening Grosbeak',
        'Hawfinch', 'Pine Grosbeak', 'Gray-crowned Rosy-Finch', 'Black Rosy-Finch', 'House Finch', 'Purple Finch',
        "Cassin's Finch", 'Common Redpoll', 'Red Crossbill', 'White-winged Crossbill', 'European Goldfinch',
        'Pine Siskin', 'Lesser Goldfinch', "Lawrence's Goldfinch", 'American Goldfinch', 'Lapland Longspur',
        'Chestnut-collared Longspur', "Smith's Longspur", "McCown's Longspur", 'Snow Bunting', 'Little Bunting',
        'Rustic Bunting', "Cassin's Sparrow", 'Grasshopper Sparrow', 'Chipping Sparrow', 'Clay-colored Sparrow',
        'Black-chinned Sparrow', 'Field Sparrow', "Brewer's Sparrow", 'Black-throated Sparrow', 'Lark Sparrow',
        'Lark Bunting', 'American Tree Sparrow', 'Fox Sparrow', 'Dark-eyed Junco', 'White-crowned Sparrow',
        'Golden-crowned Sparrow', "Harris's Sparrow", 'White-throated Sparrow', 'Sagebrush Sparrow', "Bell's Sparrow",
        'Vesper Sparrow', "LeConte's Sparrow", "Nelson's Sparrow", 'Savannah Sparrow', "Baird's Sparrow",
        'Song Sparrow', "Lincoln's Sparrow", 'Swamp Sparrow', "Abert's Towhee", 'California Towhee',
        'Rufous-crowned Sparrow', 'Green-tailed Towhee', 'Spotted Towhee', 'Yellow-breasted Chat',
        'Yellow-headed Blackbird', 'Bobolink', 'Western Meadowlark', 'Eastern Meadowlark', 'Orchard Oriole',
        'Hooded Oriole', 'Streak-backed Oriole', "Bullock's Oriole", 'Baltimore Oriole', "Scott's Oriole",
        'Red-winged Blackbird', 'Tricolored Blackbird', 'Bronzed Cowbird', 'Brown-headed Cowbird', 'Rusty Blackbird',
        "Brewer's Blackbird", 'Common Grackle', 'Great-tailed Grackle', 'Ovenbird', 'Worm-eating Warbler',
        'Louisiana Waterthrush', 'Northern Waterthrush', 'Golden-winged Warbler', 'Blue-winged Warbler',
        'Black-and-white Warbler', 'Prothonotary Warbler', 'Tennessee Warbler', 'Orange-crowned Warbler',
        "Lucy's Warbler", 'Nashville Warbler', "Virginia's Warbler", 'Connecticut Warbler', "MacGillivray's Warbler",
        'Mourning Warbler', 'Kentucky Warbler', 'Common Yellowthroat', 'Hooded Warbler', 'American Redstart',
        'Cape May Warbler', 'Cerulean Warbler', 'Northern Parula', 'Tropical Parula', 'Magnolia Warbler',
        'Bay-breasted Warbler', 'Blackburnian Warbler', 'Yellow Warbler', 'Chestnut-sided Warbler', 'Blackpoll Warbler',
        'Black-throated Blue Warbler', 'Palm Warbler', 'Pine Warbler', 'Yellow-rumped Warbler',
        'Yellow-throated Warbler', 'Prairie Warbler', "Grace's Warbler", 'Black-throated Gray Warbler',
        "Townsend's Warbler", 'Hermit Warbler', 'Black-throated Green Warbler', 'Canada Warbler', "Wilson's Warbler",
        'Red-faced Warbler', 'Painted Redstart', 'Hepatic Tanager', 'Summer Tanager', 'Scarlet Tanager',
        'Western Tanager', 'Northern Cardinal', 'Pyrrhuloxia', 'Rose-breasted Grosbeak', 'Black-headed Grosbeak',
        'Blue Grosbeak', 'Lazuli Bunting', 'Indigo Bunting', 'Varied Bunting', 'Painted Bunting', 'Dickcissel',
        'Cinnamon-rumped Seedeater', 'House Sparrow', 'Northern Red Bishop', 'Orange-cheeked Waxbill',
        'Bronze Mannikin', 'Scaly-breasted Munia', 'Pin-tailed Whydah',
    ]),

    # US: All ebird com_name's with observations in the last 10y
    #   '''
    #   http --follow 'https://ebird.org/barchart?byr=2008&r=US' \
    #       | pup '[data-species-code] json{}' \
    #       | jq 'map({species_code: ."data-species-code", com_name: .text})' \
    #       > /tmp/US.json
    #   '''
    #   import html
    #   (pd.read_json('/tmp/US.json')
    #       .applymap(html.unescape)  # Decode html entities leftover from pup
    #       .com_name
    #       .pipe(puts, f=lambda s: len(s.unique()))
    #       .pipe(lambda s:
    #           pprint.pprint(s.unique().tolist(), indent=8, width=120, compact=True)
    #       )
    #   )
    us_ebird=('ebird', [
        'White-faced Whistling-Duck', 'Black-bellied Whistling-Duck', 'Fulvous Whistling-Duck', 'Emperor Goose',
        'Snow Goose', "Ross's Goose", 'Graylag Goose', 'Swan Goose', 'Greater White-fronted Goose',
        'Lesser White-fronted Goose', 'Taiga Bean-Goose', 'Tundra Bean-Goose', 'Pink-footed Goose', 'Brant',
        'Barnacle Goose', 'Cackling Goose', 'Canada Goose', 'Hawaiian Goose', 'Red-breasted Goose', 'Mute Swan',
        'Black Swan', 'Trumpeter Swan', 'Tundra Swan', 'Whooper Swan', 'Egyptian Goose', 'Ruddy Shelduck',
        'Common Shelduck', 'Muscovy Duck', 'Ringed Teal', 'Wood Duck', 'Mandarin Duck', 'Baikal Teal', 'Garganey',
        'Blue-winged Teal', 'Cinnamon Teal', 'Northern Shoveler', 'Gadwall', 'Falcated Duck', 'Eurasian Wigeon',
        'American Wigeon', 'Laysan Duck', 'Hawaiian Duck', 'Mallard', 'Mexican Duck', 'American Black Duck',
        'Mottled Duck', 'White-cheeked Pintail', 'Northern Pintail', 'Green-winged Teal', 'Canvasback', 'Redhead',
        'Common Pochard', 'Ring-necked Duck', 'Tufted Duck', 'Greater Scaup', 'Lesser Scaup', "Steller's Eider",
        'Spectacled Eider', 'King Eider', 'Common Eider', 'Harlequin Duck', 'Surf Scoter', 'White-winged Scoter',
        'Common Scoter', 'Black Scoter', 'Long-tailed Duck', 'Bufflehead', 'Common Goldeneye', "Barrow's Goldeneye",
        'Smew', 'Hooded Merganser', 'Common Merganser', 'Red-breasted Merganser', 'Masked Duck', 'Ruddy Duck',
        'Plain Chachalaca', 'Helmeted Guineafowl', 'Mountain Quail', 'Northern Bobwhite', 'Scaled Quail',
        'California Quail', "Gambel's Quail", 'Montezuma Quail', 'Indian Peafowl', 'Japanese Quail', 'Chukar',
        'Himalayan Snowcock', "Erckel's Francolin", 'Black Francolin', 'Gray Francolin', 'Red Junglefowl',
        'Golden Pheasant', 'Ring-necked Pheasant', 'Kalij Pheasant', 'Gray Partridge', 'Ruffed Grouse',
        'Greater Sage-Grouse', 'Gunnison Sage-Grouse', 'Spruce Grouse', 'Willow Ptarmigan', 'Rock Ptarmigan',
        'White-tailed Ptarmigan', 'Dusky Grouse', 'Sooty Grouse', 'Sharp-tailed Grouse', 'Greater Prairie-Chicken',
        'Lesser Prairie-Chicken', 'Wild Turkey', 'American Flamingo', 'Greater Flamingo', 'Least Grebe',
        'Pied-billed Grebe', 'Horned Grebe', 'Red-necked Grebe', 'Eared Grebe', 'Western Grebe', "Clark's Grebe",
        'Rock Pigeon', 'White-crowned Pigeon', 'Red-billed Pigeon', 'Band-tailed Pigeon', 'Oriental Turtle-Dove',
        'Eurasian Collared-Dove', 'African Collared-Dove', 'Spotted Dove', 'Diamond Dove', 'Zebra Dove', 'Inca Dove',
        'Common Ground-Dove', 'Ruddy Ground-Dove', 'Ruddy Quail-Dove', 'Key West Quail-Dove', 'White-tipped Dove',
        'White-winged Dove', 'Zenaida Dove', 'Mourning Dove', 'Chestnut-bellied Sandgrouse', 'Smooth-billed Ani',
        'Groove-billed Ani', 'Greater Roadrunner', 'Yellow-billed Cuckoo', 'Mangrove Cuckoo', 'Black-billed Cuckoo',
        'Common Cuckoo', 'Oriental Cuckoo', 'Lesser Nighthawk', 'Common Nighthawk', 'Antillean Nighthawk',
        'Common Pauraque', 'Common Poorwill', "Chuck-will's-widow", 'Buff-collared Nightjar', 'Eastern Whip-poor-will',
        'Mexican Whip-poor-will', 'Black Swift', 'Chimney Swift', "Vaux's Swift", 'White-throated Needletail',
        'Mariana Swiftlet', 'Common Swift', 'Pacific Swift', 'White-throated Swift', 'Mexican Violetear',
        'Green-breasted Mango', "Rivoli's Hummingbird", 'Plain-capped Starthroat', 'Amethyst-throated Hummingbird',
        'Blue-throated Hummingbird', 'Lucifer Hummingbird', 'Bahama Woodstar', 'Ruby-throated Hummingbird',
        'Black-chinned Hummingbird', "Anna's Hummingbird", "Costa's Hummingbird", 'Broad-tailed Hummingbird',
        'Rufous Hummingbird', "Allen's Hummingbird", 'Calliope Hummingbird', 'Broad-billed Hummingbird',
        'Berylline Hummingbird', 'Buff-bellied Hummingbird', 'Violet-crowned Hummingbird', 'White-eared Hummingbird',
        "Ridgway's Rail", 'King Rail', 'Clapper Rail', 'Virginia Rail', 'Corn Crake', 'Rufous-necked Wood-Rail', 'Sora',
        'Common Gallinule', 'Hawaiian Coot', 'American Coot', 'Purple Gallinule', 'Gray-headed Swamphen', 'Yellow Rail',
        'Black Rail', 'Sungrebe', 'Limpkin', 'Sandhill Crane', 'Common Crane', 'Hooded Crane', 'Whooping Crane',
        'Black-necked Stilt', 'American Avocet', 'American Oystercatcher', 'Black Oystercatcher',
        'Black-bellied Plover', 'European Golden-Plover', 'American Golden-Plover', 'Pacific Golden-Plover',
        'Northern Lapwing', 'Lesser Sand-Plover', 'Greater Sand-Plover', 'Collared Plover', 'Snowy Plover',
        "Wilson's Plover", 'Common Ringed Plover', 'Semipalmated Plover', 'Piping Plover', 'Killdeer',
        'Mountain Plover', 'Northern Jacana', 'Upland Sandpiper', 'Bristle-thighed Curlew', 'Whimbrel',
        'Long-billed Curlew', 'Far Eastern Curlew', 'Bar-tailed Godwit', 'Black-tailed Godwit', 'Hudsonian Godwit',
        'Marbled Godwit', 'Ruddy Turnstone', 'Black Turnstone', 'Great Knot', 'Red Knot', 'Surfbird', 'Ruff',
        'Broad-billed Sandpiper', 'Sharp-tailed Sandpiper', 'Stilt Sandpiper', 'Curlew Sandpiper', "Temminck's Stint",
        'Long-toed Stint', 'Red-necked Stint', 'Sanderling', 'Dunlin', 'Rock Sandpiper', 'Purple Sandpiper',
        "Baird's Sandpiper", 'Little Stint', 'Least Sandpiper', 'White-rumped Sandpiper', 'Buff-breasted Sandpiper',
        'Pectoral Sandpiper', 'Semipalmated Sandpiper', 'Western Sandpiper', 'Short-billed Dowitcher',
        'Long-billed Dowitcher', 'Jack Snipe', 'American Woodcock', 'Solitary Snipe', 'Common Snipe', "Wilson's Snipe",
        'Pin-tailed Snipe', 'Terek Sandpiper', "Wilson's Phalarope", 'Red-necked Phalarope', 'Red Phalarope',
        'Common Sandpiper', 'Spotted Sandpiper', 'Green Sandpiper', 'Solitary Sandpiper', 'Gray-tailed Tattler',
        'Wandering Tattler', 'Spotted Redshank', 'Greater Yellowlegs', 'Common Greenshank', 'Willet',
        'Lesser Yellowlegs', 'Marsh Sandpiper', 'Wood Sandpiper', 'Great Skua', 'South Polar Skua', 'Pomarine Jaeger',
        'Parasitic Jaeger', 'Long-tailed Jaeger', 'Dovekie', 'Common Murre', 'Thick-billed Murre', 'Razorbill',
        'Black Guillemot', 'Pigeon Guillemot', 'Long-billed Murrelet', 'Marbled Murrelet', "Kittlitz's Murrelet",
        "Scripps's Murrelet", 'Guadalupe Murrelet', "Craveri's Murrelet", 'Ancient Murrelet', "Cassin's Auklet",
        'Parakeet Auklet', 'Least Auklet', 'Whiskered Auklet', 'Crested Auklet', 'Rhinoceros Auklet', 'Atlantic Puffin',
        'Horned Puffin', 'Tufted Puffin', 'Swallow-tailed Gull', 'Black-legged Kittiwake', 'Red-legged Kittiwake',
        'Ivory Gull', "Sabine's Gull", "Bonaparte's Gull", 'Gray-hooded Gull', 'Black-headed Gull', 'Little Gull',
        "Ross's Gull", 'Laughing Gull', "Franklin's Gull", 'Black-tailed Gull', "Heermann's Gull", 'Mew Gull',
        'Ring-billed Gull', 'Western Gull', 'Yellow-footed Gull', 'California Gull', 'Herring Gull', 'Iceland Gull',
        'Lesser Black-backed Gull', 'Slaty-backed Gull', 'Glaucous-winged Gull', 'Glaucous Gull',
        'Great Black-backed Gull', 'Kelp Gull', 'Brown Noddy', 'Black Noddy', 'Blue-gray Noddy', 'White Tern',
        'Sooty Tern', 'Gray-backed Tern', 'Bridled Tern', 'Aleutian Tern', 'Least Tern', 'Gull-billed Tern',
        'Caspian Tern', 'Black Tern', 'White-winged Tern', 'Whiskered Tern', 'Roseate Tern', 'Common Tern',
        'Arctic Tern', "Forster's Tern", 'Royal Tern', 'Sandwich Tern', 'Elegant Tern', 'Black Skimmer',
        'White-tailed Tropicbird', 'Red-billed Tropicbird', 'Red-tailed Tropicbird', 'Red-throated Loon', 'Arctic Loon',
        'Pacific Loon', 'Common Loon', 'Yellow-billed Loon', 'Yellow-nosed Albatross', "Salvin's Albatross",
        'Black-browed Albatross', 'Wandering Albatross', 'Laysan Albatross', 'Black-footed Albatross',
        'Short-tailed Albatross', "Wilson's Storm-Petrel", 'White-faced Storm-Petrel', 'Black-bellied Storm-Petrel',
        'European Storm-Petrel', 'Fork-tailed Storm-Petrel', "Leach's Storm-Petrel", "Townsend's Storm-Petrel",
        "Leach's/Townsend's Storm-Petrel (dark-rumped)", "Leach's/Townsend's Storm-Petrel (white-rumped)",
        "Swinhoe's Storm-Petrel", 'Ashy Storm-Petrel', 'Band-rumped Storm-Petrel', 'Wedge-rumped Storm-Petrel',
        'Black Storm-Petrel', "Tristram's Storm-Petrel", 'Least Storm-Petrel', 'Northern Fulmar', 'Gray-faced Petrel',
        'Kermadec Petrel', 'Trindade Petrel', 'Herald Petrel', "Murphy's Petrel", "Fea's Petrel", 'Mottled Petrel',
        'Bermuda Petrel', 'Black-capped Petrel', 'Juan Fernandez Petrel', 'Hawaiian Petrel', 'White-necked Petrel',
        'Bonin Petrel', 'Black-winged Petrel', "Cook's Petrel", "Stejneger's Petrel", "Bulwer's Petrel",
        "Jouanin's Petrel", 'Tahiti Petrel', 'White-chinned Petrel', "Cory's Shearwater", 'Pink-footed Shearwater',
        'Flesh-footed Shearwater', 'Great Shearwater', 'Wedge-tailed Shearwater', "Buller's Shearwater",
        'Sooty Shearwater', 'Short-tailed Shearwater', 'Christmas Shearwater', 'Manx Shearwater', "Newell's Shearwater",
        'Black-vented Shearwater', 'Barolo Shearwater', "Audubon's Shearwater", 'Woolly-necked Stork', 'Jabiru',
        'Wood Stork', 'Magnificent Frigatebird', 'Great Frigatebird', 'Masked Booby', 'Nazca Booby',
        'Blue-footed Booby', 'Brown Booby', 'Red-footed Booby', 'Northern Gannet', 'Anhinga', "Brandt's Cormorant",
        'Red-faced Cormorant', 'Pelagic Cormorant', 'Great Cormorant', 'Neotropic Cormorant',
        'Double-crested Cormorant', 'American White Pelican', 'Brown Pelican', 'American Bittern', 'Least Bittern',
        'Bare-throated Tiger-Heron', 'Great Blue Heron', 'Great Egret', 'Intermediate Egret', 'Little Egret',
        'Snowy Egret', 'Little Blue Heron', 'Tricolored Heron', 'Reddish Egret', 'Cattle Egret', 'Chinese Pond-Heron',
        'Green Heron', 'Black-crowned Night-Heron', 'Yellow-crowned Night-Heron', 'White Ibis', 'Glossy Ibis',
        'White-faced Ibis', 'Sacred Ibis', 'Roseate Spoonbill', 'California Condor', 'Black Vulture', 'Turkey Vulture',
        'Osprey', 'White-tailed Kite', 'Hook-billed Kite', 'Swallow-tailed Kite', 'Golden Eagle', 'Snail Kite',
        'Double-toothed Kite', 'Mississippi Kite', 'Northern Harrier', 'Sharp-shinned Hawk', "Cooper's Hawk",
        'Northern Goshawk', 'Black Kite', 'Bald Eagle', 'White-tailed Eagle', "Steller's Sea-Eagle",
        'Common Black Hawk', 'Great Black Hawk', 'Roadside Hawk', "Harris's Hawk", 'White-tailed Hawk', 'Variable Hawk',
        'Gray Hawk', 'Red-shouldered Hawk', 'Broad-winged Hawk', 'Hawaiian Hawk', 'Short-tailed Hawk',
        "Swainson's Hawk", 'Zone-tailed Hawk', 'Red-tailed Hawk', 'Rough-legged Hawk', 'Ferruginous Hawk',
        'Long-legged Buzzard', 'Barn Owl', 'Flammulated Owl', 'Whiskered Screech-Owl', 'Western Screech-Owl',
        'Eastern Screech-Owl', 'Great Horned Owl', 'Snowy Owl', 'Northern Hawk Owl', 'Northern Pygmy-Owl',
        'Ferruginous Pygmy-Owl', 'Elf Owl', 'Burrowing Owl', 'Spotted Owl', 'Barred Owl', 'Great Gray Owl',
        'Long-eared Owl', 'Stygian Owl', 'Short-eared Owl', 'Boreal Owl', 'Northern Saw-whet Owl', 'Northern Boobook',
        'Eared Quetzal', 'Elegant Trogon', 'Ringed Kingfisher', 'Belted Kingfisher', 'Amazon Kingfisher',
        'Green Kingfisher', 'Eurasian Wryneck', "Williamson's Sapsucker", 'Yellow-bellied Sapsucker',
        'Red-naped Sapsucker', 'Red-breasted Sapsucker', "Lewis's Woodpecker", 'Red-headed Woodpecker',
        'Acorn Woodpecker', 'Gila Woodpecker', 'Golden-fronted Woodpecker', 'Red-bellied Woodpecker',
        'American Three-toed Woodpecker', 'Black-backed Woodpecker', 'Downy Woodpecker', "Nuttall's Woodpecker",
        'Ladder-backed Woodpecker', 'Red-cockaded Woodpecker', 'Hairy Woodpecker', 'White-headed Woodpecker',
        'Arizona Woodpecker', 'Pileated Woodpecker', 'Northern Flicker', 'Gilded Flicker', 'Crested Caracara',
        'American Kestrel', 'Merlin', 'Eurasian Hobby', 'Aplomado Falcon', 'Gyrfalcon', 'Peregrine Falcon',
        'Prairie Falcon', 'Tanimbar Corella', 'Sulphur-crested Cockatoo', 'Salmon-crested Cockatoo', 'White Cockatoo',
        'Cockatiel', 'Rose-ringed Parakeet', 'Budgerigar', 'Rosy-faced Lovebird', 'Yellow-collared Lovebird',
        'Red-fronted Parrot', 'Monk Parakeet', 'White-winged Parakeet', 'Yellow-chevroned Parakeet',
        'Scaly-headed Parrot', 'Blue-headed Parrot', 'Red-crowned Parrot', 'Lilac-crowned Parrot', 'Red-lored Parrot',
        'Yellow-headed Parrot', 'Yellow-crowned Parrot', 'Turquoise-fronted Parrot', 'White-fronted Parrot',
        'Orange-winged Parrot', 'Burrowing Parakeet', 'Nanday Parakeet', 'Sun Parakeet', 'Blue-and-yellow Macaw',
        'Chestnut-fronted Macaw', 'Blue-crowned Parakeet', 'Green Parakeet', 'Crimson-fronted Parakeet',
        'Scarlet-fronted Parakeet', 'Mitred Parakeet', 'Red-masked Parakeet', 'White-eyed Parakeet',
        'Northern Beardless-Tyrannulet', 'White-crested Elaenia', 'Tufted Flycatcher', 'Olive-sided Flycatcher',
        'Greater Pewee', 'Western Wood-Pewee', 'Eastern Wood-Pewee', 'Cuban Pewee', 'Yellow-bellied Flycatcher',
        'Acadian Flycatcher', 'Alder Flycatcher', 'Willow Flycatcher', 'Least Flycatcher', "Hammond's Flycatcher",
        'Gray Flycatcher', 'Dusky Flycatcher', 'Pine Flycatcher', 'Pacific-slope Flycatcher', 'Cordilleran Flycatcher',
        'Buff-breasted Flycatcher', 'Black Phoebe', 'Eastern Phoebe', "Say's Phoebe", 'Vermilion Flycatcher',
        'Dusky-capped Flycatcher', 'Ash-throated Flycatcher', "Nutting's Flycatcher", 'Great Crested Flycatcher',
        'Brown-crested Flycatcher', "La Sagra's Flycatcher", 'Great Kiskadee', 'Sulphur-bellied Flycatcher',
        'Piratic Flycatcher', 'Variegated Flycatcher', 'Crowned Slaty Flycatcher', 'Tropical Kingbird',
        "Couch's Kingbird", "Cassin's Kingbird", 'Thick-billed Kingbird', 'Western Kingbird', 'Eastern Kingbird',
        'Gray Kingbird', 'Loggerhead Kingbird', 'Scissor-tailed Flycatcher', 'Fork-tailed Flycatcher',
        'Gray-collared Becard', 'Rose-throated Becard', 'Red-backed Shrike', 'Brown Shrike', 'Loggerhead Shrike',
        'Northern Shrike', 'Black-capped Vireo', 'White-eyed Vireo', 'Thick-billed Vireo', 'Cuban Vireo',
        "Bell's Vireo", 'Gray Vireo', "Hutton's Vireo", 'Yellow-throated Vireo', "Cassin's Vireo", 'Blue-headed Vireo',
        'Plumbeous Vireo', 'Philadelphia Vireo', 'Warbling Vireo', 'Red-eyed Vireo', 'Yellow-green Vireo',
        'Black-whiskered Vireo', 'Hawaii Elepaio', 'Kauai Elepaio', 'Oahu Elepaio', 'Canada Jay',
        'Black-throated Magpie-Jay', 'Brown Jay', 'Green Jay', 'Pinyon Jay', "Steller's Jay", 'Blue Jay',
        'Florida Scrub-Jay', 'Island Scrub-Jay', 'California Scrub-Jay', "Woodhouse's Scrub-Jay", 'Mexican Jay',
        'Black-billed Magpie', 'Yellow-billed Magpie', "Clark's Nutcracker", 'House Crow', 'American Crow',
        'Northwestern Crow', 'Tamaulipas Crow', 'Fish Crow', 'Chihuahuan Raven', 'Common Raven', 'Horned Lark',
        'Eurasian Skylark', 'Northern Rough-winged Swallow', 'Purple Martin', 'Brown-chested Martin', 'Tree Swallow',
        'Violet-green Swallow', 'Bahama Swallow', 'Bank Swallow', 'Barn Swallow', 'Cliff Swallow', 'Cave Swallow',
        'Common House-Martin', 'Carolina Chickadee', 'Black-capped Chickadee', 'Mountain Chickadee',
        'Mexican Chickadee', 'Chestnut-backed Chickadee', 'Boreal Chickadee', 'Gray-headed Chickadee',
        'Bridled Titmouse', 'Oak Titmouse', 'Juniper Titmouse', 'Tufted Titmouse', 'Black-crested Titmouse',
        'Great Tit', 'Verdin', 'Bushtit', 'Red-breasted Nuthatch', 'White-breasted Nuthatch', 'Pygmy Nuthatch',
        'Brown-headed Nuthatch', 'Brown Creeper', 'Rock Wren', 'Canyon Wren', 'House Wren', 'Pacific Wren',
        'Winter Wren', 'Sedge Wren', 'Marsh Wren', 'Carolina Wren', "Bewick's Wren", 'Cactus Wren', 'Sinaloa Wren',
        'Blue-gray Gnatcatcher', 'California Gnatcatcher', 'Black-tailed Gnatcatcher', 'Black-capped Gnatcatcher',
        'American Dipper', 'Red-vented Bulbul', 'Red-whiskered Bulbul', 'Golden-crowned Kinglet',
        'Ruby-crowned Kinglet', 'Japanese Bush Warbler', 'Wood Warbler', 'Yellow-browed Warbler', 'Dusky Warbler',
        'Willow Warbler', 'Common Chiffchaff', 'Arctic Warbler', 'Kamchatka Leaf Warbler', 'Thick-billed Warbler',
        'Sedge Warbler', "Blyth's Reed Warbler", 'Millerbird', "Middendorff's Grasshopper-Warbler",
        'Lanceolated Warbler', 'Eurasian River Warbler', 'Wrentit', 'Japanese White-eye', 'Chinese Hwamei',
        'Greater Necklaced Laughingthrush', 'Red-billed Leiothrix', 'Gray-streaked Flycatcher', 'Dark-sided Flycatcher',
        'Asian Brown Flycatcher', 'White-rumped Shama', 'European Robin', 'Rufous-tailed Robin', 'Siberian Blue Robin',
        'Bluethroat', 'Siberian Rubythroat', 'Red-flanked Bluetail', 'Taiga Flycatcher', 'Common Redstart',
        'Siberian Stonechat', 'Northern Wheatear', 'Pied Wheatear', 'Eastern Bluebird', 'Western Bluebird',
        'Mountain Bluebird', "Townsend's Solitaire", 'Brown-backed Solitaire', 'Omao', 'Puaiohi', 'Varied Thrush',
        'Orange-billed Nightingale-Thrush', 'Veery', 'Gray-cheeked Thrush', "Bicknell's Thrush", "Swainson's Thrush",
        'Hermit Thrush', 'Wood Thrush', 'Aztec Thrush', 'Redwing', 'White-throated Thrush', 'Clay-colored Thrush',
        'American Robin', 'Rufous-backed Robin', 'Red-legged Thrush', 'Eyebrowed Thrush', 'Fieldfare', 'Dusky Thrush',
        "Naumann's Thrush", 'Blue Mockingbird', 'Gray Catbird', 'Curve-billed Thrasher', 'Brown Thrasher',
        'Long-billed Thrasher', "Bendire's Thrasher", 'California Thrasher', "LeConte's Thrasher", 'Crissal Thrasher',
        'Sage Thrasher', 'Bahama Mockingbird', 'Tropical Mockingbird', 'Northern Mockingbird', 'Common Hill Myna',
        'European Starling', 'Common Myna', 'Siberian Accentor', 'Gray Wagtail', 'Eastern Yellow Wagtail',
        'Citrine Wagtail', 'White Wagtail', 'Tree Pipit', 'Olive-backed Pipit', 'Pechora Pipit', 'Red-throated Pipit',
        'American Pipit', "Sprague's Pipit", 'Bohemian Waxwing', 'Cedar Waxwing', 'Phainopepla', 'Olive Warbler',
        'Common Chaffinch', 'Brambling', 'Evening Grosbeak', 'Hawfinch', 'Akikiki', 'Maui Alauahio', 'Palila',
        'Nihoa Finch', 'Akohekohe', 'Apapane', 'Iiwi', 'Maui Parrotbill', 'Akiapolaau', 'Anianiau', 'Hawaii Amakihi',
        'Oahu Amakihi', 'Kauai Amakihi', 'Hawaii Creeper', 'Akekee', 'Hawaii Akepa', 'Common Rosefinch',
        "Pallas's Rosefinch", 'Pine Grosbeak', 'Eurasian Bullfinch', 'Asian Rosy-Finch', 'Gray-crowned Rosy-Finch',
        'Black Rosy-Finch', 'Brown-capped Rosy-Finch', 'House Finch', 'Purple Finch', "Cassin's Finch",
        'European Greenfinch', 'Oriental Greenfinch', 'Yellow-fronted Canary', 'Common Redpoll', 'Hoary Redpoll',
        'Red Crossbill', 'Cassia Crossbill', 'White-winged Crossbill', 'European Goldfinch', 'Eurasian Siskin',
        'Pine Siskin', 'Lesser Goldfinch', "Lawrence's Goldfinch", 'American Goldfinch', 'Lapland Longspur',
        'Chestnut-collared Longspur', "Smith's Longspur", "McCown's Longspur", 'Snow Bunting', "McKay's Bunting",
        'Pine Bunting', "Pallas's Bunting", 'Yellow-breasted Bunting', 'Little Bunting', 'Rustic Bunting',
        'Gray Bunting', 'Rufous-winged Sparrow', "Botteri's Sparrow", "Cassin's Sparrow", "Bachman's Sparrow",
        'Grasshopper Sparrow', 'Olive Sparrow', 'Chipping Sparrow', 'Clay-colored Sparrow', 'Black-chinned Sparrow',
        'Field Sparrow', "Brewer's Sparrow", 'Black-throated Sparrow', 'Five-striped Sparrow', 'Lark Sparrow',
        'Lark Bunting', 'American Tree Sparrow', 'Fox Sparrow', 'Dark-eyed Junco', 'Yellow-eyed Junco',
        'White-crowned Sparrow', 'Golden-crowned Sparrow', "Harris's Sparrow", 'White-throated Sparrow',
        'Sagebrush Sparrow', "Bell's Sparrow", 'Striped Sparrow', 'Vesper Sparrow', "LeConte's Sparrow",
        'Seaside Sparrow', "Nelson's Sparrow", 'Saltmarsh Sparrow', 'Savannah Sparrow', "Baird's Sparrow",
        "Henslow's Sparrow", 'Song Sparrow', "Lincoln's Sparrow", 'Swamp Sparrow', 'Canyon Towhee', "Abert's Towhee",
        'California Towhee', 'Rufous-crowned Sparrow', 'Green-tailed Towhee', 'Spotted Towhee', 'Eastern Towhee',
        'Western Spindalis', 'Yellow-breasted Chat', 'Yellow-headed Blackbird', 'Bobolink', 'Western Meadowlark',
        'Eastern Meadowlark', 'Black-vented Oriole', 'Orchard Oriole', 'Hooded Oriole', 'Streak-backed Oriole',
        "Bullock's Oriole", 'Spot-breasted Oriole', 'Altamira Oriole', "Audubon's Oriole", 'Baltimore Oriole',
        'Black-backed Oriole', "Scott's Oriole", 'Red-winged Blackbird', 'Tricolored Blackbird', 'Shiny Cowbird',
        'Bronzed Cowbird', 'Brown-headed Cowbird', 'Rusty Blackbird', "Brewer's Blackbird", 'Common Grackle',
        'Boat-tailed Grackle', 'Great-tailed Grackle', 'Ovenbird', 'Worm-eating Warbler', 'Louisiana Waterthrush',
        'Northern Waterthrush', 'Golden-winged Warbler', 'Blue-winged Warbler', 'Black-and-white Warbler',
        'Prothonotary Warbler', "Swainson's Warbler", 'Crescent-chested Warbler', 'Tennessee Warbler',
        'Orange-crowned Warbler', 'Colima Warbler', "Lucy's Warbler", 'Nashville Warbler', "Virginia's Warbler",
        'Connecticut Warbler', 'Gray-crowned Yellowthroat', "MacGillivray's Warbler", 'Mourning Warbler',
        'Kentucky Warbler', 'Common Yellowthroat', 'Hooded Warbler', 'American Redstart', "Kirtland's Warbler",
        'Cape May Warbler', 'Cerulean Warbler', 'Northern Parula', 'Tropical Parula', 'Magnolia Warbler',
        'Bay-breasted Warbler', 'Blackburnian Warbler', 'Yellow Warbler', 'Chestnut-sided Warbler', 'Blackpoll Warbler',
        'Black-throated Blue Warbler', 'Palm Warbler', 'Pine Warbler', 'Yellow-rumped Warbler',
        'Yellow-throated Warbler', 'Prairie Warbler', "Grace's Warbler", 'Black-throated Gray Warbler',
        "Townsend's Warbler", 'Hermit Warbler', 'Golden-cheeked Warbler', 'Black-throated Green Warbler',
        'Fan-tailed Warbler', 'Rufous-capped Warbler', 'Golden-crowned Warbler', 'Canada Warbler', "Wilson's Warbler",
        'Red-faced Warbler', 'Red Warbler', 'Painted Redstart', 'Slate-throated Redstart', 'Hepatic Tanager',
        'Summer Tanager', 'Scarlet Tanager', 'Western Tanager', 'Flame-colored Tanager', 'Crimson-collared Grosbeak',
        'Northern Cardinal', 'Pyrrhuloxia', 'Yellow Grosbeak', 'Rose-breasted Grosbeak', 'Black-headed Grosbeak',
        'Blue Bunting', 'Blue Grosbeak', 'Lazuli Bunting', 'Indigo Bunting', 'Varied Bunting', 'Painted Bunting',
        'Dickcissel', 'Red-crested Cardinal', 'Yellow-billed Cardinal', 'Red-legged Honeycreeper', 'Saffron Finch',
        "Morelet's Seedeater", 'Cinnamon-rumped Seedeater', 'Bananaquit', 'Cuban Grassquit', 'Yellow-faced Grassquit',
        'Black-faced Grassquit', 'House Sparrow', 'Eurasian Tree Sparrow', 'Northern Red Bishop', 'Lavender Waxbill',
        'Orange-cheeked Waxbill', 'Black-rumped Waxbill', 'Common Waxbill', 'Red-cheeked Cordonbleu', 'Red Avadavat',
        'Zebra Finch', 'Bronze Mannikin', 'African Silverbill', 'Scaly-breasted Munia', 'Tricolored Munia',
        'Chestnut Munia', 'Java Sparrow', 'Pin-tailed Whydah',
    ]),

    # CR: All ebird com_name's with observations in the last 10y
    #   '''
    #   http --follow 'https://ebird.org/barchart?byr=2008&r=CR' \
    #       | pup '[data-species-code] json{}' \
    #       | jq 'map({species_code: ."data-species-code", com_name: .text})' \
    #       > /tmp/CR.json
    #   '''
    #   import html
    #   (pd.read_json('/tmp/CR.json')
    #       .applymap(html.unescape)  # Decode html entities leftover from pup
    #       .com_name
    #       .pipe(puts, f=lambda s: len(s.unique()))
    #       .pipe(lambda s:
    #           pprint.pprint(s.unique().tolist(), indent=8, width=120, compact=True)
    #       )
    #   )
    cr_ebird=('ebird', [
        'Highland Tinamou', 'Great Tinamou', 'Little Tinamou', 'Slaty-breasted Tinamou', 'Thicket Tinamou',
        'Black-bellied Whistling-Duck', 'Fulvous Whistling-Duck', 'Comb Duck', 'Muscovy Duck', 'Blue-winged Teal',
        'Cinnamon Teal', 'Northern Shoveler', 'American Wigeon', 'Mallard', 'White-cheeked Pintail', 'Northern Pintail',
        'Green-winged Teal', 'Canvasback', 'Redhead', 'Ring-necked Duck', 'Lesser Scaup', 'Hooded Merganser',
        'Masked Duck', 'Ruddy Duck', 'Plain Chachalaca', 'Gray-headed Chachalaca', 'Crested Guan', 'Black Guan',
        'Great Curassow', 'Tawny-faced Quail', 'Buffy-crowned Wood-Partridge', 'Crested Bobwhite', 'Marbled Wood-Quail',
        'Black-eared Wood-Quail', 'Black-breasted Wood-Quail', 'Spotted Wood-Quail', 'Least Grebe', 'Pied-billed Grebe',
        'Rock Pigeon', 'Pale-vented Pigeon', 'Scaled Pigeon', 'White-crowned Pigeon', 'Red-billed Pigeon',
        'Band-tailed Pigeon', 'Ruddy Pigeon', 'Short-billed Pigeon', 'Eurasian Collared-Dove', 'Inca Dove',
        'Common Ground-Dove', 'Plain-breasted Ground-Dove', 'Ruddy Ground-Dove', 'Blue Ground-Dove',
        'Maroon-chested Ground-Dove', 'Ruddy Quail-Dove', 'Violaceous Quail-Dove', 'Olive-backed Quail-Dove',
        'White-tipped Dove', 'Gray-chested Dove', 'Gray-headed Dove', 'Buff-fronted Quail-Dove',
        'Purplish-backed Quail-Dove', 'Chiriqui Quail-Dove', 'White-winged Dove', 'Mourning Dove', 'Greater Ani',
        'Smooth-billed Ani', 'Groove-billed Ani', 'Striped Cuckoo', 'Pheasant Cuckoo', 'Lesser Ground-Cuckoo',
        'Rufous-vented Ground-Cuckoo', 'Squirrel Cuckoo', 'Yellow-billed Cuckoo', 'Mangrove Cuckoo', 'Cocos Cuckoo',
        'Black-billed Cuckoo', 'Lesser Nighthawk', 'Common Nighthawk', 'Short-tailed Nighthawk', 'Common Pauraque',
        'White-tailed Nightjar', 'Ocellated Poorwill', "Chuck-will's-widow", 'Rufous Nightjar',
        'Eastern Whip-poor-will', 'Dusky Nightjar', 'Great Potoo', 'Common Potoo', 'Northern Potoo', 'Oilbird',
        'Black Swift', 'White-chinned Swift', 'Spot-fronted Swift', 'Chestnut-collared Swift', 'White-collared Swift',
        'Chimney Swift', "Vaux's Swift", 'Costa Rican Swift', 'Gray-rumped Swift', 'Lesser Swallow-tailed Swift',
        'White-necked Jacobin', 'White-tipped Sicklebill', 'Bronzy Hermit', 'Band-tailed Barbthroat', 'Green Hermit',
        'Long-billed Hermit', 'Stripe-throated Hermit', 'Green-fronted Lancebill', 'Brown Violetear',
        'Lesser Violetear', 'Purple-crowned Fairy', 'Green-breasted Mango', 'Veraguan Mango', 'Green Thorntail',
        'Rufous-crested Coquette', 'Black-crested Coquette', 'White-crested Coquette', 'Green-crowned Brilliant',
        'Talamanca Hummingbird', 'Long-billed Starthroat', 'Plain-capped Starthroat', 'Fiery-throated Hummingbird',
        'White-bellied Mountain-gem', 'Purple-throated Mountain-gem', 'White-throated Mountain-gem',
        'Magenta-throated Woodstar', 'Ruby-throated Hummingbird', 'Volcano Hummingbird', 'Scintillant Hummingbird',
        "Canivet's Emerald", 'Garden Emerald', 'Violet-headed Hummingbird', 'Scaly-breasted Hummingbird',
        'Violet Sabrewing', 'Bronze-tailed Plumeleteer', 'Crowned Woodnymph', 'Stripe-tailed Hummingbird',
        'Black-bellied Hummingbird', 'White-tailed Emerald', 'Coppery-headed Emerald', 'Snowcap',
        'Blue-chested Hummingbird', 'Charming Hummingbird', 'Mangrove Hummingbird', 'Blue-tailed Hummingbird',
        'Steely-vented Hummingbird', 'Snowy-bellied Hummingbird', 'Rufous-tailed Hummingbird', 'Cinnamon Hummingbird',
        'Sapphire-throated Hummingbird', 'Blue-throated Goldentail', 'Mangrove Rail', 'Paint-billed Crake',
        'Spotted Rail', 'Uniform Crake', 'Rufous-necked Wood-Rail', 'Russet-naped Wood-Rail', 'Gray-cowled Wood-Rail',
        'Sora', 'Common Gallinule', 'American Coot', 'Purple Gallinule', 'Ocellated Crake', 'Yellow-breasted Crake',
        'White-throated Crake', 'Gray-breasted Crake', 'Sungrebe', 'Limpkin', 'Double-striped Thick-knee',
        'Black-necked Stilt', 'American Avocet', 'American Oystercatcher', 'Black-bellied Plover',
        'American Golden-Plover', 'Pacific Golden-Plover', 'Southern Lapwing', 'Collared Plover', 'Snowy Plover',
        "Wilson's Plover", 'Semipalmated Plover', 'Killdeer', 'Northern Jacana', 'Wattled Jacana', 'Upland Sandpiper',
        'Whimbrel', 'Long-billed Curlew', 'Hudsonian Godwit', 'Marbled Godwit', 'Ruddy Turnstone', 'Red Knot',
        'Surfbird', 'Stilt Sandpiper', 'Sanderling', 'Dunlin', "Baird's Sandpiper", 'Least Sandpiper',
        'White-rumped Sandpiper', 'Buff-breasted Sandpiper', 'Pectoral Sandpiper', 'Semipalmated Sandpiper',
        'Western Sandpiper', 'Short-billed Dowitcher', 'Long-billed Dowitcher', "Wilson's Snipe", "Wilson's Phalarope",
        'Red-necked Phalarope', 'Red Phalarope', 'Spotted Sandpiper', 'Solitary Sandpiper', 'Wandering Tattler',
        'Greater Yellowlegs', 'Willet', 'Lesser Yellowlegs', 'South Polar Skua', 'Pomarine Jaeger', 'Parasitic Jaeger',
        'Long-tailed Jaeger', 'Swallow-tailed Gull', 'Black-legged Kittiwake', "Sabine's Gull", "Bonaparte's Gull",
        'Laughing Gull', "Franklin's Gull", 'Ring-billed Gull', 'Herring Gull', 'Great Black-backed Gull', 'Kelp Gull',
        'Brown Noddy', 'Black Noddy', 'White Tern', 'Sooty Tern', 'Bridled Tern', 'Least Tern', 'Yellow-billed Tern',
        'Gull-billed Tern', 'Caspian Tern', 'Inca Tern', 'Black Tern', 'Common Tern', 'Arctic Tern', "Forster's Tern",
        'Royal Tern', 'Sandwich Tern', 'Elegant Tern', 'Black Skimmer', 'Sunbittern', 'Red-billed Tropicbird',
        "Wilson's Storm-Petrel", "Leach's Storm-Petrel", "Leach's/Townsend's Storm-Petrel (dark-rumped)",
        'Band-rumped Storm-Petrel', 'Wedge-rumped Storm-Petrel', 'Black Storm-Petrel', "Markham's Storm-Petrel",
        'Least Storm-Petrel', 'Galapagos Petrel', 'Tahiti Petrel', "Parkinson's Petrel", 'Pink-footed Shearwater',
        'Wedge-tailed Shearwater', 'Sooty Shearwater', 'Christmas Shearwater', 'Galapagos Shearwater',
        'Black-vented Shearwater', "Audubon's Shearwater", 'Maguari Stork', 'Jabiru', 'Wood Stork',
        'Magnificent Frigatebird', 'Great Frigatebird', 'Masked Booby', 'Nazca Booby', 'Blue-footed Booby',
        'Brown Booby', 'Red-footed Booby', 'Anhinga', 'Neotropic Cormorant', 'American White Pelican', 'Brown Pelican',
        'Pinnated Bittern', 'American Bittern', 'Least Bittern', 'Rufescent Tiger-Heron', 'Fasciated Tiger-Heron',
        'Bare-throated Tiger-Heron', 'Great Blue Heron', 'Great Egret', 'Snowy Egret', 'Little Blue Heron',
        'Tricolored Heron', 'Reddish Egret', 'Cattle Egret', 'Green Heron', 'Striated Heron', 'Agami Heron',
        'Whistling Heron', 'Black-crowned Night-Heron', 'Yellow-crowned Night-Heron', 'Boat-billed Heron', 'White Ibis',
        'Glossy Ibis', 'Green Ibis', 'Roseate Spoonbill', 'King Vulture', 'Black Vulture', 'Turkey Vulture',
        'Lesser Yellow-headed Vulture', 'Osprey', 'Pearl Kite', 'White-tailed Kite', 'Hook-billed Kite',
        'Gray-headed Kite', 'Swallow-tailed Kite', 'Crested Eagle', 'Harpy Eagle', 'Black Hawk-Eagle',
        'Ornate Hawk-Eagle', 'Black-and-white Hawk-Eagle', 'Black-collared Hawk', 'Snail Kite', 'Double-toothed Kite',
        'Mississippi Kite', 'Plumbeous Kite', 'Northern Harrier', 'Gray-bellied Hawk', 'Tiny Hawk',
        'Sharp-shinned Hawk', "Cooper's Hawk", 'Bicolored Hawk', 'Crane Hawk', 'Common Black Hawk', 'Savanna Hawk',
        'Great Black Hawk', 'Solitary Eagle', 'Barred Hawk', 'Roadside Hawk', "Harris's Hawk", 'White-tailed Hawk',
        'White Hawk', 'Semiplumbeous Hawk', 'Gray Hawk', 'Gray-lined Hawk', 'Broad-winged Hawk', 'Short-tailed Hawk',
        "Swainson's Hawk", 'Zone-tailed Hawk', 'Red-tailed Hawk', 'Barn Owl', 'Bare-shanked Screech-Owl',
        'Tropical Screech-Owl', 'Middle American Screech-Owl', 'Pacific Screech-Owl', 'Crested Owl', 'Spectacled Owl',
        'Great Horned Owl', 'Costa Rican Pygmy-Owl', 'Central American Pygmy-Owl', 'Ferruginous Pygmy-Owl',
        'Mottled Owl', 'Black-and-white Owl', 'Striped Owl', 'Unspotted Saw-whet Owl', 'Resplendent Quetzal',
        'Lattice-tailed Trogon', 'Slaty-tailed Trogon', 'Black-headed Trogon', "Baird's Trogon", 'Gartered Trogon',
        'Black-throated Trogon', 'Elegant Trogon', 'Orange-bellied Trogon', 'Collared Trogon', 'Tody Motmot',
        "Lesson's Motmot", 'Rufous Motmot', 'Keel-billed Motmot', 'Broad-billed Motmot', 'Turquoise-browed Motmot',
        'Ringed Kingfisher', 'Belted Kingfisher', 'Amazon Kingfisher', 'American Pygmy Kingfisher', 'Green Kingfisher',
        'Green-and-rufous Kingfisher', 'White-necked Puffbird', 'Pied Puffbird', 'White-whiskered Puffbird',
        'Lanceolated Monklet', 'White-fronted Nunbird', 'Rufous-tailed Jacamar', 'Great Jacamar', 'Red-headed Barbet',
        'Prong-billed Barbet', 'Northern Emerald-Toucanet', 'Collared Aracari', 'Fiery-billed Aracari',
        'Yellow-eared Toucanet', 'Yellow-throated Toucan', 'Keel-billed Toucan', 'Olivaceous Piculet',
        'Yellow-bellied Sapsucker', 'Acorn Woodpecker', 'Golden-naped Woodpecker', 'Black-cheeked Woodpecker',
        'Red-crowned Woodpecker', "Hoffmann's Woodpecker", 'Hairy Woodpecker', 'Smoky-brown Woodpecker',
        'Red-rumped Woodpecker', 'Pale-billed Woodpecker', 'Lineated Woodpecker', 'Cinnamon Woodpecker',
        'Chestnut-colored Woodpecker', 'Rufous-winged Woodpecker', 'Golden-olive Woodpecker', 'Barred Forest-Falcon',
        'Slaty-backed Forest-Falcon', 'Collared Forest-Falcon', 'Red-throated Caracara', 'Crested Caracara',
        'Yellow-headed Caracara', 'Laughing Falcon', 'American Kestrel', 'Merlin', 'Aplomado Falcon', 'Bat Falcon',
        'Peregrine Falcon', 'Red-fronted Parrotlet', 'Barred Parakeet', 'Orange-chinned Parakeet',
        'Brown-hooded Parrot', 'Blue-headed Parrot', 'White-crowned Parrot', 'Red-lored Parrot', 'Yellow-naped Parrot',
        'White-fronted Parrot', 'Mealy Parrot', 'Sulphur-winged Parakeet', 'Olive-throated Parakeet',
        'Orange-fronted Parakeet', 'Brown-throated Parakeet', 'Great Green Macaw', 'Scarlet Macaw',
        'Crimson-fronted Parakeet', 'Rufous-rumped Antwren', 'Fasciated Antshrike', 'Great Antshrike',
        'Barred Antshrike', 'Black-crowned Antshrike', 'Black-hooded Antshrike', 'Russet Antshrike', 'Plain Antvireo',
        'Streak-crowned Antvireo', 'Spot-crowned Antvireo', 'Checker-throated Antwren', 'White-flanked Antwren',
        'Slaty Antwren', 'Dot-winged Antwren', 'Dusky Antbird', 'Bare-crowned Antbird', 'Chestnut-backed Antbird',
        'Dull-mantled Antbird', "Zeledon's Antbird", 'Bicolored Antbird', 'Spotted Antbird', 'Ocellated Antbird',
        'Black-crowned Antpitta', 'Scaled Antpitta', 'Streak-chested Antpitta', 'Thicket Antpitta',
        'Ochre-breasted Antpitta', 'Silvery-fronted Tapaculo', 'Black-faced Antthrush', 'Black-headed Antthrush',
        'Rufous-breasted Antthrush', 'Tawny-throated Leaftosser', 'Scaly-throated Leaftosser',
        'Gray-throated Leaftosser', 'Olivaceous Woodcreeper', 'Long-tailed Woodcreeper', 'Ruddy Woodcreeper',
        'Tawny-winged Woodcreeper', 'Plain-brown Woodcreeper', 'Wedge-billed Woodcreeper',
        'Northern Barred-Woodcreeper', 'Black-banded Woodcreeper', 'Strong-billed Woodcreeper', 'Cocoa Woodcreeper',
        'Ivory-billed Woodcreeper', 'Black-striped Woodcreeper', 'Spotted Woodcreeper', 'Brown-billed Scythebill',
        'Streak-headed Woodcreeper', 'Spot-crowned Woodcreeper', 'Plain Xenops', 'Streaked Xenops', 'Buffy Tuftedcheek',
        'Buff-fronted Foliage-gleaner', 'Scaly-throated Foliage-gleaner', 'Lineated Foliage-gleaner',
        'Ruddy Foliage-gleaner', 'Streak-breasted Treehunter', 'Buff-throated Foliage-gleaner',
        'Chiriqui Foliage-gleaner', 'Striped Woodhaunter', 'Spotted Barbtail', 'Ruddy Treerunner',
        'Red-faced Spinetail', 'Slaty Spinetail', 'Pale-breasted Spinetail', 'Yellow-bellied Tyrannulet',
        'Brown-capped Tyrannulet', 'Northern Beardless-Tyrannulet', 'Southern Beardless-Tyrannulet',
        'Mouse-colored Tyrannulet', 'Cocos Flycatcher', 'Yellow Tyrannulet', 'Yellow-crowned Tyrannulet',
        'Greenish Elaenia', 'Yellow-bellied Elaenia', 'Lesser Elaenia', 'Mountain Elaenia', 'Torrent Tyrannulet',
        'Olive-striped Flycatcher', 'Ochre-bellied Flycatcher', 'Sepia-capped Flycatcher', 'Slaty-capped Flycatcher',
        'Rufous-browed Tyrannulet', 'Rough-legged Tyrannulet', 'Mistletoe Tyrannulet', 'Northern Scrub-Flycatcher',
        'Black-capped Pygmy-Tyrant', 'Scale-crested Pygmy-Tyrant', 'Northern Bentbill', 'Slate-headed Tody-Flycatcher',
        'Common Tody-Flycatcher', 'Black-headed Tody-Flycatcher', 'Eye-ringed Flatbill', 'Yellow-olive Flycatcher',
        'Yellow-margined Flycatcher', 'Stub-tailed Spadebill', 'White-throated Spadebill', 'Golden-crowned Spadebill',
        'Royal Flycatcher', 'Ruddy-tailed Flycatcher', 'Sulphur-rumped Flycatcher', 'Black-tailed Flycatcher',
        'Bran-colored Flycatcher', 'Tawny-chested Flycatcher', 'Tufted Flycatcher', 'Olive-sided Flycatcher',
        'Dark Pewee', 'Ochraceous Pewee', 'Western Wood-Pewee', 'Eastern Wood-Pewee', 'Tropical Pewee',
        'Yellow-bellied Flycatcher', 'Acadian Flycatcher', 'Alder Flycatcher', 'Willow Flycatcher',
        'White-throated Flycatcher', 'Least Flycatcher', 'Yellowish Flycatcher', 'Black-capped Flycatcher',
        'Black Phoebe', 'Long-tailed Tyrant', 'Bright-rumped Attila', 'Rufous Mourner', 'Dusky-capped Flycatcher',
        'Panama Flycatcher', "Nutting's Flycatcher", 'Great Crested Flycatcher', 'Brown-crested Flycatcher',
        'Great Kiskadee', 'Boat-billed Flycatcher', 'Rusty-margined Flycatcher', 'Social Flycatcher',
        'Gray-capped Flycatcher', 'White-ringed Flycatcher', 'Golden-bellied Flycatcher', 'Streaked Flycatcher',
        'Sulphur-bellied Flycatcher', 'Piratic Flycatcher', 'Tropical Kingbird', 'Western Kingbird', 'Eastern Kingbird',
        'Gray Kingbird', 'Scissor-tailed Flycatcher', 'Fork-tailed Flycatcher', 'Sharpbill',
        'Purple-throated Fruitcrow', 'Bare-necked Umbrellabird', 'Lovely Cotinga', 'Turquoise Cotinga', 'Rufous Piha',
        'Three-wattled Bellbird', 'Yellow-billed Cotinga', 'Snowy Cotinga', 'Lance-tailed Manakin',
        'Long-tailed Manakin', 'White-ruffed Manakin', 'Blue-crowned Manakin', 'White-collared Manakin',
        'Orange-collared Manakin', 'White-crowned Manakin', 'Red-capped Manakin', 'Gray-headed Piprites',
        'Black-crowned Tityra', 'Masked Tityra', 'Northern Schiffornis', 'Speckled Mourner', 'Barred Becard',
        'Cinnamon Becard', 'White-winged Becard', 'Black-and-white Becard', 'Rose-throated Becard',
        'Rufous-browed Peppershrike', 'Scrub Greenlet', 'Green Shrike-Vireo', 'Tawny-crowned Greenlet',
        'Lesser Greenlet', 'White-eyed Vireo', 'Mangrove Vireo', 'Yellow-throated Vireo', 'Yellow-winged Vireo',
        'Blue-headed Vireo', 'Philadelphia Vireo', 'Warbling Vireo', 'Brown-capped Vireo', 'Red-eyed Vireo',
        'Yellow-green Vireo', 'Black-whiskered Vireo', 'Silvery-throated Jay', 'Azure-hooded Jay',
        'White-throated Magpie-Jay', 'Brown Jay', 'Black-chested Jay', 'Blue-and-white Swallow',
        'Northern Rough-winged Swallow', 'Southern Rough-winged Swallow', 'Purple Martin', 'Gray-breasted Martin',
        'Brown-chested Martin', 'Tree Swallow', 'Mangrove Swallow', 'Violet-green Swallow', 'Bank Swallow',
        'Barn Swallow', 'Cliff Swallow', 'Cave Swallow', 'Rock Wren', 'Nightingale Wren', 'Scaly-breasted Wren',
        'House Wren', 'Ochraceous Wren', 'Timberline Wren', 'Sedge Wren', 'Band-backed Wren', 'Rufous-naped Wren',
        'Black-bellied Wren', 'Rufous-breasted Wren', 'Spot-breasted Wren', 'Black-throated Wren', 'Banded Wren',
        'Rufous-and-white Wren', 'Stripe-breasted Wren', "Cabanis's Wren", 'Canebrake Wren', 'Isthmian Wren',
        'Riverside Wren', 'Bay Wren', 'White-breasted Wood-Wren', 'Gray-breasted Wood-Wren', 'Song Wren',
        'Tawny-faced Gnatwren', 'Long-billed Gnatwren', 'White-lored Gnatcatcher', 'Tropical Gnatcatcher',
        'American Dipper', 'Black-faced Solitaire', 'Black-billed Nightingale-Thrush',
        'Orange-billed Nightingale-Thrush', 'Slaty-backed Nightingale-Thrush', 'Ruddy-capped Nightingale-Thrush',
        'Black-headed Nightingale-Thrush', 'Veery', 'Gray-cheeked Thrush', "Swainson's Thrush", 'Wood Thrush',
        'Mountain Thrush', 'Pale-vented Thrush', 'White-throated Thrush', 'Clay-colored Thrush', 'Sooty Thrush',
        'Gray Catbird', 'Tropical Mockingbird', 'American Pipit', 'Cedar Waxwing', 'Black-and-yellow Silky-flycatcher',
        'Long-tailed Silky-flycatcher', 'Golden-browed Chlorophonia', 'Scrub Euphonia', 'Yellow-crowned Euphonia',
        'Thick-billed Euphonia', 'Yellow-throated Euphonia', 'Elegant Euphonia', 'Spot-crowned Euphonia',
        'Olive-backed Euphonia', 'White-vented Euphonia', 'Tawny-capped Euphonia', 'Lesser Goldfinch',
        'Yellow-bellied Siskin', 'Rosy Thrush-Tanager', 'Ashy-throated Chlorospingus', 'Sooty-capped Chlorospingus',
        'Common Chlorospingus', 'Stripe-headed Sparrow', "Botteri's Sparrow", 'Grasshopper Sparrow', 'Olive Sparrow',
        'Black-striped Sparrow', 'Clay-colored Sparrow', 'Costa Rican Brushfinch', 'Orange-billed Sparrow',
        'Chestnut-capped Brushfinch', 'Sooty-faced Finch', 'Volcano Junco', 'Rufous-collared Sparrow',
        'White-crowned Sparrow', 'Savannah Sparrow', "Lincoln's Sparrow", 'Large-footed Finch',
        'White-eared Ground-Sparrow', "Cabanis's Ground-Sparrow", 'Rusty Sparrow', 'Yellow-thighed Finch',
        'White-naped Brushfinch', 'Wrenthrush', 'Yellow-breasted Chat', 'Yellow-headed Blackbird', 'Bobolink',
        'Eastern Meadowlark', 'Red-breasted Meadowlark', 'Yellow-billed Cacique', 'Crested Oropendola',
        'Chestnut-headed Oropendola', 'Montezuma Oropendola', 'Scarlet-rumped Cacique', 'Black-cowled Oriole',
        'Orchard Oriole', 'Yellow-backed Oriole', 'Yellow-tailed Oriole', 'Streak-backed Oriole', "Bullock's Oriole",
        'Spot-breasted Oriole', 'Baltimore Oriole', 'Red-winged Blackbird', 'Shiny Cowbird', 'Bronzed Cowbird',
        'Giant Cowbird', 'Melodious Blackbird', 'Great-tailed Grackle', 'Nicaraguan Grackle', 'Ovenbird',
        'Worm-eating Warbler', 'Louisiana Waterthrush', 'Northern Waterthrush', 'Golden-winged Warbler',
        'Blue-winged Warbler', 'Black-and-white Warbler', 'Prothonotary Warbler', 'Flame-throated Warbler',
        'Tennessee Warbler', 'Orange-crowned Warbler', 'Nashville Warbler', 'Connecticut Warbler',
        'Gray-crowned Yellowthroat', "MacGillivray's Warbler", 'Mourning Warbler', 'Kentucky Warbler',
        'Olive-crowned Yellowthroat', 'Common Yellowthroat', 'Hooded Warbler', 'American Redstart', 'Cape May Warbler',
        'Cerulean Warbler', 'Northern Parula', 'Tropical Parula', 'Magnolia Warbler', 'Bay-breasted Warbler',
        'Blackburnian Warbler', 'Yellow Warbler', 'Chestnut-sided Warbler', 'Blackpoll Warbler',
        'Black-throated Blue Warbler', 'Palm Warbler', 'Pine Warbler', 'Yellow-rumped Warbler',
        'Yellow-throated Warbler', 'Prairie Warbler', "Townsend's Warbler", 'Hermit Warbler', 'Golden-cheeked Warbler',
        'Black-throated Green Warbler', 'Rufous-capped Warbler', 'Black-cheeked Warbler', 'Golden-crowned Warbler',
        'Costa Rican Warbler', 'Buff-rumped Warbler', 'Canada Warbler', "Wilson's Warbler", 'Slate-throated Redstart',
        'Collared Redstart', 'Dusky-faced Tanager', 'Hepatic Tanager', 'Summer Tanager', 'Scarlet Tanager',
        'Western Tanager', 'Flame-colored Tanager', 'White-winged Tanager', 'Red-crowned Ant-Tanager',
        'Red-throated Ant-Tanager', 'Black-cheeked Ant-Tanager', "Carmiol's Tanager", 'Black-faced Grosbeak',
        'Black-thighed Grosbeak', 'Rose-breasted Grosbeak', 'Blue Seedeater', 'Blue-black Grosbeak', 'Blue Grosbeak',
        'Indigo Bunting', 'Painted Bunting', 'Dickcissel', 'Gray-headed Tanager', 'White-shouldered Tanager',
        'Tawny-crested Tanager', 'White-lined Tanager', 'White-throated Shrike-Tanager', 'Crimson-collared Tanager',
        'Flame-rumped Tanager', 'Scarlet-rumped Tanager', 'Blue-and-gold Tanager', 'Blue-gray Tanager',
        'Yellow-winged Tanager', 'Palm Tanager', 'Speckled Tanager', 'Golden-hooded Tanager', 'Spangle-cheeked Tanager',
        'Plain-colored Tanager', 'Rufous-winged Tanager', 'Bay-headed Tanager', 'Emerald Tanager',
        'Silver-throated Tanager', 'Scarlet-thighed Dacnis', 'Blue Dacnis', 'Shining Honeycreeper',
        'Red-legged Honeycreeper', 'Green Honeycreeper', 'Sulphur-rumped Tanager', 'Black-and-yellow Tanager',
        'Slaty Flowerpiercer', 'Slaty Finch', 'Peg-billed Finch', 'Wedge-tailed Grass-Finch', 'Blue-black Grassquit',
        'Lined Seedeater', 'Ruddy-breasted Seedeater', 'Thick-billed Seed-Finch', 'Nicaraguan Seed-Finch',
        'Variable Seedeater', "Morelet's Seedeater", 'Yellow-bellied Seedeater', 'Slate-colored Seedeater',
        'Bananaquit', 'Yellow-faced Grassquit', 'Cocos Finch', 'Buff-throated Saltator', 'Black-headed Saltator',
        'Grayish Saltator', 'Streaked Saltator', 'Slate-colored Grosbeak', 'House Sparrow', 'Tricolored Munia',
    ]),

)
