# pyright docs:
# - https://github.com/microsoft/pyright/blob/main/docs/configuration.md
[tool.pyright]
include = [
  ".",
]
exclude = [
  "**/__pycache__",
  "**/*.egg-info",
  "_attic",
  "bin",
  "data",
  "vm-bin",
]
ignore = [
  "pydub",
  "sp14",
]
