apiVersion: v1
kind: Service
metadata:
  name: api
  labels:
    app: api
spec:
  type: LoadBalancer
  # Static ip managed in https://console.cloud.google.com/networking/addresses
  loadBalancerIP: 104.197.235.14
  selector:
    app: api
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
    name: http
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: default
  name: api
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: 'bubo/api:0'
        command: ['bin/run-prod']
