# Docs
# - https://facebook.github.io/react-native/docs/integration-with-existing-apps#configuring-cocoapods-dependencies
# - https://shift.infinite.red/beginner-s-guide-to-using-cocoapods-with-react-native-46cb4d372995
#
# Troubleshooting
# - `pod install` -> error "Unable to find a specification for `FooBar`"
#   - Try inspecting stuff
#     $ pod repo list
#     $ pod search FooBar
#     $ pod spec cat FooBar
#   - Try updating the pod master repo [https://github.com/CocoaPods/CocoaPods/issues/3877]
#     $ pod repo update
#   - Try resetting the pod master repo [https://stackoverflow.com/a/32850706/397334]
#     $ pod repo remove master
#     $ pod setup

platform :ios, '10.0'
use_frameworks!

workspace 'Birdgram.xcworkspace'

def bubo_pods
  pod 'Alamofire', '~> 4.8.0'
  pod 'AudioKit', '~> 4.5'
  # pod 'Surge', '~> 2.2.0' # XXX Vendored [why?]
  pod 'SigmaSwiftStatistics', '~> 8.0'
  pod 'SwiftyJSON', '~> 4.0'
  pod 'Yams', '~> 1.0.1'
end

def birdgram_pods
  pod 'PromisesSwift', '~> 1.2.4' # Moved here b/c it gave me trouble in the Bubo-macos target
end

def all_pods
  bubo_pods
  birdgram_pods
end

# TODO How to fix warning "contains framework ... for which the Podfile does not contain host targets"?
target 'Bubo' do
  project 'Bubo/Bubo.xcodeproj'
  bubo_pods
end

target 'Bubo-macos' do
  project 'Bubo/Bubo.xcodeproj'
  platform :osx, '10.11'
  bubo_pods
end

target 'Playgrounds' do
  project 'Playgrounds/Playgrounds.xcodeproj'
  all_pods
end

target 'Birdgram' do

  project 'Birdgram.xcodeproj'
  all_pods

  # NOTE react-native-config tried to add this line but I never realized I needed to `pod install`
  # during the setup, so I ended up doing all the linking stuff myself (I guess), so I later
  # disabled this to avoid thrash...
  # pod 'react-native-config', :path => '../node_modules/react-native-config'

  # # This causes warnings. Commented out for now.
  # target 'BirdgramTests' do
  #   inherit! :search_paths
  # end

end
