# Docs
# - https://facebook.github.io/react-native/docs/integration-with-existing-apps#configuring-cocoapods-dependencies
# - https://shift.infinite.red/beginner-s-guide-to-using-cocoapods-with-react-native-46cb4d372995
#
# Troubleshooting
# - `pod install` -> error "Unable to find a specification for `FooBar`"
#   - Try inspecting stuff
#     $ pod repo list
#     $ pod search FooBar
#     $ pod spec cat FooBar
#   - Try updating the pod master repo [https://github.com/CocoaPods/CocoaPods/issues/3877]
#     $ pod repo update
#   - Try resetting the pod master repo [https://stackoverflow.com/a/32850706/397334]
#     $ pod repo remove master
#     $ pod setup

platform :ios, '10.0'
use_frameworks!

workspace 'Birdgram.xcworkspace'

def bubo_pods
  pod 'Alamofire', '~> 4.9'
  # XXX Only load AudioKit for Birdgram and not Bubo to avoid logged warnings on app startup:
  #  - "Class ... is implemented in both .../Bubo.framework/Bubo and .../Birdgram.app/Birdgram.
  #    One of the two will be used. Which one is undefined."
  # pod 'AudioKit', '~> 4.5'
  # pod 'Surge', '~> 2.2.0' # XXX Vendored [why?]
  pod 'SigmaSwiftStatistics', '~> 9.0'
  pod 'SwiftyJSON', '~> 5.0'
  # pod 'TagLibIOS', '~> 0.3.0' # XXX ios only (can't test locally on mac)
  pod 'Yams', '~> 2.0'
end

def birdgram_pods
  pod 'AudioKit', '~> 4.9.3'
  pod 'PromisesSwift', '~> 1.2.8' # Moved here b/c it gave me trouble in the Bubo-macos target
end

def all_pods
  bubo_pods
  birdgram_pods
end

# TODO How to fix warning "contains framework ... for which the Podfile does not contain host targets"?
target 'Bubo' do
  project 'Bubo/Bubo.xcodeproj'
  bubo_pods
end

target 'Bubo-macos' do
  project 'Bubo/Bubo.xcodeproj'
  platform :osx, '10.11'
  bubo_pods
end

target 'Playgrounds' do
  project 'Playgrounds/Playgrounds.xcodeproj'
  all_pods
end

target 'Birdgram' do

  project 'Birdgram.xcodeproj'
  all_pods

  # HACK Prevent `react-native link` from adding pod deps here
  # - They typically try to depend on the 'React' pod, which is deprecated and causes problems
  #   - e.g. https://github.com/react-native-community/react-native-camera/issues/1747
  #   - e.g. https://github.com/bugsnag/bugsnag-react-native/issues/193
  # - Workaround: do the link steps manually for each native dep (usually in their README)
  #   - e.g. https://github.com/react-native-community/react-native-device-info#manual
  #
  # Disabled from `react-native link react-native-config`
  # pod 'react-native-config', :path => '../node_modules/react-native-config'
  #
  # Disabled from `react-native link react-native-device-info`
  # pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'
  #
  # Disabled from `react-native link react-native-sentry`
  #   - https://sentry.io/onboarding/dan-brown/birdgram/configure/react-native/
  # pod 'SentryReactNative', :path => '../node_modules/react-native-sentry'
  #
  # Disabled from `react-native link react-native-sqlite-plugin-legacy-support`
  # pod 'SQLiteSupport', :path => '../node_modules/react-native-sqlite-plugin-legacy-support'
  #
  # Disabled from `react-native link react-native link react-native-safe-area-context`
  # pod 'react-native-safe-area-context', :path => '../node_modules/react-native-safe-area-context'

  # This causes warnings. Commented out for now.
  # target 'BirdgramTests' do
  #   inherit! :search_paths
  # end

end
