#!/bin/bash -eux

dir="`dirname "$0"`"

# Debug
# - Add shaded box at bottom
# - HACK Label with ' ' b/c icon.png is way too low-res for any text to be useful (e.g. 'Debug'/'D')
app-icon label -i "$dir"/icon.png -o "$dir"/icon.debug.png --bottom ' '
(cd "$dir"/Debug && app-icon generate -i ../icon.debug.png)

# Release
(cd "$dir"/Release && app-icon generate -i ../icon.png)
