#!/bin/bash -eu

# Parse args
if [ $# -ne 1 ]; then echo >&2 "Usage: $0 <disk-name>"; exit 1; fi
disk_name="$1"; shift

disk_dev="/dev/disk/by-id/google-$disk_name"
mnt_dir='/mnt/disks/disk-bubo-data'

# Noop if already mounted
if mountpoint -q "$mnt_dir"; then
  exit 0
fi

echo "Mounting: disk[$disk_dev] at $mnt_dir"

# Mount disk
# - https://cloud.google.com/compute/docs/disks/add-persistent-disk
# - If we want to use cloud-init/cloud-config instead:
#   - https://cloud.google.com/container-optimized-os/docs/resources/faq#how_do_i_format_and_mount_disks
#   - https://cloud.google.com/container-optimized-os/docs/how-to/create-configure-instance
sudo mkdir -p "$mnt_dir"
sudo mount -o discard,defaults "$disk_dev" "$mnt_dir"
