name: bubo-features
channels:
- conda-forge
dependencies:

# Core python
- python=3.6
- pip==9.0.3

# 3rd-party libs
- feather-format=0.4.0
# - ffmpeg=3.4.1 # For pydub [XXX Use docker/brew ffmpeg so we can build with libmp3lame. TODO How to ffmpeg+libmp3lame with conda?]
- lightgbm=2.1.2
- matplotlib=2.1.1 # TODO How to install 2.2.x without conflicts?
- ncurses=5.9  # HACK Pin ncurses=5.9 to workaround lib error with ncurses=6:
# - "ImportError: dlopen(.../readline.cpython-36m-darwin.so, 2): Library not loaded: @rpath/libncursesw.5.dylib"
- numpy=1.14.5 # Keep this up to date so that pip deps don't install a newer numpy without openblas
- pillow=4.3.0 # pillow brings in mkl [TODO How do we want this to work?]
- pandas=0.23.0 # Duped in pip deps
- scikit-learn=0.19.1 # Duped in pip deps
- scipy=1.1.0
- sox=14.4.2 # For pydub
- sqlite=3.24.0
- xgboost=0.72

# openblas vs. mkl
# - References
#   - http://markus-beuckelmann.de/blog/boosting-numpy-blas.html
#   - http://blog.nguyenvq.com/blog/2014/11/10/optimized-r-and-python-standard-blas-vs-atlas-vs-openblas-vs-mkl/
#   - https://github.com/scikit-learn/scikit-learn/issues/9429
# - Takeaways
#   - Make sure to use mkl or openblas, and don't worry too much about which one
#   - mkl is maybe ~25% faster than openblas, but mkl crashes on fft, so let's stick with openblas for now
#   - conda defaults to mkl
- blas=1.1=openblas
- openblas=0.2.20
# - mkl=2018.0.2 # XXX "Internal error occurred" in numpy.fft [https://gist.github.com/jdanbrown/0d57ee6d159672be957957537a03fa19]

# R
# - rpy2=2.8.5 # TODO How to install 2.9.3 without conflicts? [HACK We install rpy2==2.9.2 in requirements.txt]
- rpy2=2.9.3 # TODO TODO Hail mary...
# - gfortran_linux-64=7.2.0 # TODO Doesn't work on osx! (duh) -- TODO TODO maybe libgfortran instead? what was the rpy2 error again?

# R packages
# - See Rdepends.R for non-conda deps
- r-devtools=1.13.5
- r-ggally=1.3.2
# - r-ggmap=2.6.1  # -> devtools::install_github("dkahle/ggmap") to get bugfixes in 2.7 (e.g. https://github.com/dkahle/ggmap/issues/188)
- r-ggridges=0.5.0
- r-irkernel=0.8.11
- r-mapproj=1.2.6
# - r-sf=0.6 # 0.6-3 in Rdepends.R
- r-skimr=1.0.2
- r-tidyverse=1.1.1 # TODO How to install 1.2.1 without conflicts? [conflicts with what?]
# - seewave
- fftw=3.3.7
- libsndfile=1.0.27
- r-rgl=0.98.1 # FIXME Usage fails when trying to load libintl (repro: seewave spectro3D)

# pip deps
# - Keep pip deps in reqs.txt so we can workaround https://github.com/pypa/pip/issues/2837
#   - We have to -U manually because we can't do it in here
#     - https://github.com/conda/conda/issues/6805
#   - We could -e in here except it causes other problems
#     - https://github.com/conda/conda/issues/5861
#     - https://github.com/pypa/pip/issues/4688
#
# HACK Disabled to split up the docker build, since a fresh `conda update` takes a while
# - pip:
#   - -r requirements.txt
