name: bubo-features
channels:
- conda-forge
dependencies:

# Core python
- python=3.6.5
- pip==9.0.3

# 3rd-party libs
- matplotlib=2.1.1 # TODO How to install 2.2.x without conflicts?
- pillow=4.3.0 # pillow brings in mkl [TODO How do we want this to work?]
- pandas=0.23.0 # Duped below in pip deps
- scikit-learn=0.19.1
- scipy=1.1.0

# openblas vs. mkl
- openblas=0.2.20
# - mkl=2018.0.2  # XXX "Internal error occurred" in numpy.fft [https://gist.github.com/jdanbrown/0d57ee6d159672be957957537a03fa19]

# R
- rpy2=2.8.5 # TODO How to install 2.9.3 without conflicts? [HACK We install rpy2==2.9.2 in requirements.txt]

# R packages
- r-devtools=1.13.5
- r-ggally=1.3.2
- r-ggridges=0.5.0
- r-irkernel=0.8.11
- r-tidyverse=1.1.1 # TODO How to install 1.2.1 without conflicts?

# TODO R packages that don't have conda packages

# lookup
#   devtools::install_github('jimhester/lookup')

# viridis
#   install.packages('viridis')

# seewave
#   install.packages('seewave')
#   install.packages('fftw')
- fftw=3.3.7
- libsndfile=1.0.27
- r-rgl=0.98.1 # FIXME Usage fails when trying to load libintl (repro: seewave spectro3D)

# pip deps
# - Keep pip deps in reqs.txt so we can workaround https://github.com/pypa/pip/issues/2837
#   - We have to -U manually because we can't do it in here
#     - https://github.com/conda/conda/issues/6805
#   - We could -e in here except it causes other problems
#     - https://github.com/conda/conda/issues/5861
#     - https://github.com/pypa/pip/issues/4688
- pip:
  - -r requirements.txt
